### PR TITLE
disable server name check for sentinel

### LINKED ISSUE #3193: Redis and Sentinel with TLS fails hostname verification
**What happened**:
JuiceFS fails to connect to Sentinel, throwing the error `sentinel: GetMasterAddrByName master="mymaster" failed: x509: certificate is valid for <hostname> not for master,<hostname>` 

```
Jan 21 20:47:50 k3s01 juicefs[3661184]: 2023/01/21 20:47:50.775641 juicefs[3661184] <INFO>: Meta address: rediss://mymaster,sentinel-0.sentinel-d.juicefs.svc.k3s.guiltyspark.net:26379,sentinel-0.sentinel-d.juicefs.svc.brg-k3s.guiltyspark.net:26379,sentinel-0.sentinel-d.juicefs.svc.k3s.fra.ovh.guiltyspark.net:26379/0?pool_size=100&idle_timeout=180 [interface.go:402]
Jan 21 20:47:50 k3s01 juicefs[3661184]: redis: 2023/01/21 20:47:50 sentinel.go:514: sentinel: GetMasterAddrByName master="mymaster" failed: x509: certificate is valid for sentinel-0.sentinel-d.juicefs.svc.k3s.guiltyspark.net, not mymaster,sentinel-0.sentinel-d.juicefs.svc.k3s.guiltyspark.net:26379,sentinel-0.sentinel-d.juicefs.svc.brg-k3s.guiltyspark.net:26379,sentinel-0.sentinel-d.juicefs.svc.k3s.fra.ovh.guiltyspark.net:26379
Jan 21 20:47:50 k3s01 juicefs[3661184]: redis: 2023/01/21 20:47:50 sentinel.go:514: sentinel: GetMasterAddrByName master="mymaster" failed: x509: certificate is valid for sentinel-0.sentinel-d.juicefs.svc.k3s.fra.ovh.guiltyspark.net, not mymaster,sentinel-0.sentinel-d.juicefs.svc.k3s.guiltyspark.net:26379,sentinel-0.sentinel-d.juicefs.svc.brg-k3s.guiltyspark.net:26379,sentinel-0.sentinel-d.juicefs.svc.k3s.fra.ovh.guiltyspark.net:26379
Jan 21 20:47:51 k3s01 juicefs[3661184]: redis: 2023/01/21 20:47:51 sentinel.go:514: sentinel: GetMasterAddrByName master="mymaster" failed: x509: certificate is valid for sentinel-0.sentinel-d.juicefs.svc.brg-k3s.guiltyspark.net, not mymaster,sentinel-0.sentinel-d.juicefs.svc.k3s.guiltyspark.net:26379,sentinel-0.sentinel-d.juicefs.svc.brg-k3s.guiltyspark.net:26379,sentinel-0.sentinel-d.juicefs.svc.k3s.fra.ovh.guiltyspark.net:26379
Jan 21 20:47:51 k3s01 juicefs[3661184]: 2023/01/21 20:47:51.008915 juicefs[3661184] <WARNING>: parse info: redis: all sentinels specified in configuration are unreachable [redis.go:2858]
```

**What you expected to happen**:
JuiceFS correctly parses the hostname from the connection string when verifying the TLS certificate.

**How to reproduce it (as minimally and precisely as possible)**:
Configure a redis/sentinel setup to utilize TLS, use the connection string with rediss:// :
export META_PASSWORD=<redis_password>
export SENTINEL_PASSWORD=<sentintel_password>
export REDIS_ENDPOINT=rediss://mymaster,sentinel-0.test.local:26379
/usr/local/bin/juicefs mount $REDIS_ENDPOINT $MOUNTPOINT

**Anything else we need to know?**
If i disable TLS for the sentinel and redis, connection works fine with same connection string.

I have also used the same TLS redis/sentinel setup for Gitea (https://github.com/go-gitea/gitea) which is also based on `go-redis` without any issues.

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: `juicefs version 1.0.2+2022-10-13.514ef03`
- Cloud provider or hardware configuration running JuiceFS: HP DL360 G7
- OS (e.g `cat /etc/os-release`): `Ubuntu 22.04.1 LTS (GNU/Linux 5.15.0-56-generic x86_64)`
- Kernel (e.g. `uname -a`): `Linux k3s01.har.guiltyspark.net 5.15.0-56-generic #62-Ubuntu SMP Tue Nov 22 19:54:14 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`
- Object storage (cloud provider and region, or self maintained): Self maintained MinIO `minio version RELEASE.2023-01-12T02-06-16Z`
- Metadata engine info (version, cloud provider managed or self maintained): Self maintained Redis `Redis 7.0.8 (00000000/0) 64 bit`
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): Self-Hosted kubernetes setup

### PR DESCRIPTION
**Pull request by davies**
close #3193

### CODE REVIEW

File: pkg/meta/redis.go [hunk 1]
```diff
@@ -101,6 +101,7 @@ func newRedisMeta(driver, addr string, conf *Config) (Meta, error) {
 	readTimeout := query.duration("read-timeout", "read_timeout", time.Second*30)
 	writeTimeout := query.duration("write-timeout", "write_timeout", time.Second*5)
 	routeRead := query.pop("route-read")
+	skipVerify := query.pop("insecureSkipVerify")
```
Comment (SandyXSD) [inline pkg/meta/redis.go:104]: `insecure-skip-verify`?
