### PR TITLE
chunk: fix the issue that staging file may be uploaded for many times

### LINKED ISSUE #3143: Writeback cache synchronization issue
**What happened**:
JuiceFS appears to have a writeback cache synchronization issue.  Example below may be exacerbated by slow IO and intolerance for misbehavior of the storage provider (STORJ), but it seems to me that the root cause is within JuiceFS.

See chunk 11008_0_4194304 in attached log; several parallel upload attempts (resulting in server errors), continuing to try to upload after file has been deleted (at time 21:32:04), and other general signs of missing synchronization.  Also appears (not observable in log below) as though --upload-delay is not being fully obeyed (uploads begin within about one second of file creation). This example is very repeatable. This problem does not occur without --writeback in the mount command.

**What you expected to happen**:
One concurrent upload attempt per chunk, and no attempt to continue uploading significantly after chunk has been deleted locally.

**How to reproduce it (as minimally and precisely as possible)**:
Mount command: juicefs mount --no-usage-report --cache-size 512 --writeback -o allow_other --upload-delay 5 --backup-meta 0 --max-uploads 5 --verbose sqlite3://storj-test.db /jfs

Test scenario: create 10 4MB files in rapid succession:
    for i in {1..10}; do dd if=/dev/urandom bs=1M count=4 of=./test${i}; done

**Environment**:
- JuiceFS version: juicefs version 1.0.3+2022-12-27.ec6c8abd
- OS: Linux (AlmaLinux 8.7)
- Kernel: 4.18.0-425.3.1.el8.x86_64
- Object storage: STORJ
- Metadata engine info: SQLite

**Log**:
See [juicefs-storj-writeback-issue.log](https://github.com/juicedata/juicefs/files/10328057/juicefs-storj-writeback-issue.log).  Reflects that I have placed additional DEBUG statements just before and after s3.go:Put()'s call to s3.PutObject() to help clarify the misbehavior.  Redacted my IP with <MY_IP>, juicefs cache path with <JFS_CACHE>

### PR DESCRIPTION
**Pull request by SandyXSD**
close #3143 
For simplicity mutex/atomic is not used to control the status of block uploading or not. It's still possible that a block is uploaded for more than one time, but the possibility and limit should be much smaller.

### CODE REVIEW

File: pkg/chunk/cached_store.go [hunk 1]
```diff
@@ -709,7 +711,7 @@ func NewCachedStore(storage object.ObjectStorage, config Config, reg prometheus.
 	store.initMetrics()
 	store.bcache = newCacheManager(&config, reg, func(key, fpath string, force bool) bool {
 		if force {
-			return store.addDelayedStaging(key, fpath, time.Time{}, true)
+			return store.addDelayedStaging(key, fpath, time.Now(), true)
```
Comment (davies) [inline pkg/chunk/cached_store.go:714]: fi.ModTime()

Comment (SandyXSD) [reply pkg/chunk/cached_store.go]: [32ec27a](https://github.com/juicedata/juicefs/pull/3157/commits/32ec27ab6ab51adeb07276fbb5ebaec5db75dc7a)
