### PR TITLE
object: fix client dial delay and prefer ipv6

### LINKED ISSUE #6749: Broken HTTP Dial for Object-Storage
**What would you like to be added**:
That the Dialer who does the http calls to the Object Storage backend prefers IPv6 over IPv4 and disables either IPv4 or IPv6 when the protocol isnt setup.

This behaviour should be somewhat inline to https://www.rfc-editor.org/rfc/rfc8305#section-3

```
The algorithm proceeds as follows: if a positive AAAA response (a
   response with at least one valid AAAA record) is received first, the
   first IPv6 connection attempt is immediately started.  If a positive
   A response is received first due to reordering, the client SHOULD
   wait a short time for the AAAA response to ensure that preference is
   given to IPv6 (it is common for the AAAA response to follow the A
   response by a few milliseconds).  This delay will be referred to as
   the "Resolution Delay".  The recommended value for the Resolution
   Delay is 50 milliseconds.  If a positive AAAA response is received
within the Resolution Delay period, the client immediately starts the
   IPv6 connection attempt.  If a negative AAAA response (no error, no
   data) is received within the Resolution Delay period or the AAAA
   response has not been received by the end of the Resolution Delay
   period, the client SHOULD proceed to sorting addresses (see
   [Section 4](https://www.rfc-editor.org/rfc/rfc8305#section-4)) and staggered connection attempts (see [Section 5](https://www.rfc-editor.org/rfc/rfc8305#section-5)) using
   any IPv4 addresses returned so far.  If the AAAA response arrives
   while these connection attempts are in progress but before any
   connection has been established, then the newly received IPv6
   addresses are incorporated into the list of available candidate
   addresses (see [Section 6](https://www.rfc-editor.org/rfc/rfc8305#section-6)) and the process of connection attempts will
   continue with the IPv6
addresses added, until one connection is
   established.
```

**Why is this needed**:

The behavior is more expected and it fixes random Timeouts.

The Dialer  (pkg/object/restful.go) in its current state is more or less "broken".
Currently it resolves all of the IPs of a host, including both v4 and v6, and picks one randomly in a loop until we have a connection.

On either v4 only and v6 only hosts, when the Host that we want to dial has dual stack enabled, will the Dialer try randomly to connect to one of the given IPs. 
This leads to frequent timeout, although the network side is configured correctly.

### PR DESCRIPTION
**Pull request by jiefenghuang**
- take over #6750
- close #6749

### CODE REVIEW

File: pkg/object/restful.go [hunk 1]
```diff
@@ -46,32 +155,23 @@ func init() {
...
+				dialer := &net.Dialer{Timeout: time.Second * 10}
+				if ip := net.ParseIP(host); ip != nil {
+					return dialer.DialContext(ctx, network, net.JoinHostPort(ip.String(), port))
+				}
 				ips, err := resolver.Fetch(host)
 				if err != nil {
 					return nil, err
 				}
 				if len(ips) == 0 {
 					return nil, fmt.Errorf("No such host: %s", host)
```
Comment (solracsf) [inline pkg/object/restful.go]:
```suggestion
					return nil, &net.DNSError{Err: "no such host", Name: host, IsNotFound: true}
```

File: pkg/object/restful.go [hunk 2]
```diff
@@ -35,6 +35,115 @@ import (
...
+			if res.error == nil {
+				return res.Conn, nil
+			}
+			if res.primary {
+				primary = res
+			} else {
+				fallback = res
+			}
+			if primary.done && fallback.done {
+				return nil, primary.error
```
Comment (solracsf) [inline pkg/object/restful.go]:
```suggestion
				return nil, errors.Join(primary.error, fallback.error)
```

File: pkg/object/restful.go [hunk 3]
```diff
@@ -46,32 +155,23 @@ func init() {
...
 			WriteBufferSize:       32 << 10,
 			DialContext: func(ctx context.Context, network string, address string) (net.Conn, error) {
-				separator := strings.LastIndex(address, ":")
-				host := address[:separator]
-				port := address[separator:]
+				host, port, err := net.SplitHostPort(address)
+				if err != nil {
+					return nil, err
+				}
+				dialer := &net.Dialer{Timeout: time.Second * 10}
```
Comment (solracsf) [inline pkg/object/restful.go]: Move dialer instantiation outside the DialContext closure?

**Comment by scrapes** [comment]
Looks good. 
In the dialRandom i would setup a check on len == 1 to skip directly to dialing the single IP.

The DNS Cache Used is pretty old and looks unmaintained ( Last commit 13 years ago). Its only a very small project with a map from Host to addresses. Maybe its easier to just fork it to have more control over it or copy it into the codebase.

The reason i am mention this is to add a Remove function to the dns cache wich will remove single IPs from the dns cache. Or we could implement a super simple negative cache on top of it to skip the dialing of known bad connections.

**Comment by jiefenghuang** [comment]
"In the dialRandom i would setup a check on len == 1 to skip directly to dialing the single IP."
I think there’s no need to add extra logic for this.

"The reason i am mention this is to add a Remove function to the dns cache wich will remove single IPs from the dns cache. Or we could implement a super simple negative cache on top of it to skip the dialing of known bad connections."
It might be caused by a temporary network issue, so let’s keep the existing logic for now.

**Comment by scrapes** [comment]
> "In the dialRandom i would setup a check on len == 1 to skip directly to dialing the single IP." I think there’s no need to add extra logic for this.
> 
> "The reason i am mention this is to add a Remove function to the dns cache wich will remove single IPs from the dns cache. Or we could implement a super simple negative cache on top of it to skip the dialing of known bad connections." It might be caused by a temporary network issue, so let’s keep the existing logic for now.

Yes but the Address would be back in cache after the next cache refresh.
But i agree, seperate issue
