### PR TITLE
sync: fix nfs path and list

### LINKED ISSUE #4140: NFS sync: put root dir failed
```bash
$ ./juicefs sync -l --dirs --perms ~/src/test/ nfs://localhost:/srv/home/test/
2023/11/06 15:09:05.055276 juicefs[673496] <ERROR>: Failed to copy data of  in 5.068782142s: rpc: GARBAGE_ARGS - rpc arguments cannot be XDR decoded [sync.go:540]
2023/11/06 15:09:05.055341 juicefs[673496] <ERROR>: Failed to copy object : rpc: GARBAGE_ARGS - rpc arguments cannot be XDR decoded [sync.go:626]
```

### PR DESCRIPTION
**Pull request by Hexilee**
close #4140

### CODE REVIEW

File: pkg/sync/sync.go [hunk 1]
```diff
@@ -681,12 +681,12 @@ func startSingleProducer(tasks chan<- object.Object, src, dst object.ObjectStora
 	start, end := config.Start, config.End
 	logger.Debugf("maxResults: %d, defaultPartSize: %d, maxBlock: %d", maxResults, defaultPartSize, maxBlock)
 
-	srckeys, err := ListAll(src, prefix, start, end, !config.Links)
```
Comment (zhijian-pro) [inline pkg/sync/sync.go:684]: The list interface should follows links by default

Comment (Hexilee) [reply pkg/sync/sync.go]: reverted
