### PR TITLE
CI: fix the random test

### LINKED ISSUE #5659: TestFSOps: expect errno 0 but got is a directory
**What happened**:
https://github.com/juicedata/juicefs/actions/runs/13323319491/job/37211692074?pr=5573

```
=== RUN   TestFSOps
    random_test.go:2144: [rapid] failed after 4105 tests: expect errno 0 but got is a directory
        To reproduce, specify -run="TestFSOps" -rapid.failfile="testdata/rapid/TestFSOps/TestFSOps-20250214054809-17988.fail" (or -rapid.seed=8427566)
        Failed test output:
    random_test.go:126: [rapid] draw sid: 0x0
    random_test.go:2144: [rapid] draw action: "Mkdir"
    random_test.go:163: [rapid] draw uid: 0x0
    random_test.go:164: [rapid] draw gid: 0x0
    random_test.go:176: [rapid] draw node: 0x1
    random_test.go:1037: [rapid] draw name: "A"
    random_test.go:1038: [rapid] draw mode: 0x0
    random_test.go:1042: parent ino 1
    random_test.go:1046: dir ino 2
    random_test.go:2144: [rapid] draw action: "Mknod"
    random_test.go:163: [rapid] draw uid: 0x0
    random_test.go:164: [rapid] draw gid: 0x0
    random_test.go:176: [rapid] draw node: 0x1
    random_test.go:1057: [rapid] draw name: "?"
    random_test.go:1061: [rapid] draw type: 0x1
    random_test.go:1062: [rapid] draw mode: 0x0
    random_test.go:2144: [rapid] draw action: "Rename"
    random_test.go:1183: [rapid] draw name: "A"
    random_test.go:163: [rapid] draw uid: 0x0
    random_test.go:164: [rapid] draw gid: 0x0
    random_test.go:176: [rapid] draw node: 0x1
    random_test.go:421: [rapid] draw child: "?"
    random_test.go:163: [rapid] draw uid: 0x0
    random_test.go:164: [rapid] draw gid: 0x0
    random_test.go:176: [rapid] draw node: 0x1
    random_test.go:1221: expect errno 0 but got is a directory
--- FAIL: TestFSOps (39.67s)
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

### LINKED ISSUE #5679: CI: Flock test failed.
**What happened**:
https://github.com/juicedata/juicefs/actions/runs/13404626272/job/37442216353
```

go test ./pkg/meta/... -rapid.meta=sqlite3://test.db -rapid.seed=21172 -rapid.checks=100000 -rapid.steps=200 -run "TestFSOps" -v -failfast -count=1 -timeout=30m -cover -coverpkg=./pkg/...,./cmd/... -args -test.gocoverdir="/home/runner/work/juicefs/juicefs/cover"
warning: no packages being tested depend on matches for pattern ./cmd/...
	github.com/juicedata/juicefs/pkg/meta/pb		coverage: 0.0% of statements
=== RUN   TestFSOps
    random_test.go:2159: [rapid] failed after 0 tests: expect [] but got []
        To reproduce, specify -run="TestFSOps" -rapid.failfile="testdata/rapid/TestFSOps/TestFSOps-2025021903[11](https://github.com/juicedata/juicefs/actions/runs/13404626272/job/37442217461#step:6:12)06-2750.fail" (or -rapid.seed=21172)
        Failed test output:
    random_test.go:[12](https://github.com/juicedata/juicefs/actions/runs/13404626272/job/37442217461#step:6:13)6: [rapid] draw sid: 0x0
    random_test.go:2159: [rapid] draw action: "Flock"
    random_test.go:163: [rapid] draw uid: 0x0
    random_test.go:164: [rapid] draw gid: 0x0
    random_test.go:176: [rapid] draw node: 0x1
    random_test.go:1928: [rapid] draw owner: 0x0
    random_test.go:1929: [rapid] draw typ: 0x0
    random_test.go:1971: expect [] but got []
--- FAIL: TestFSOps (3.81s)

go test ./pkg/meta/... -rapid.meta=redis://127.0.0.1:6379/1 -rapid.seed=7908 -rapid.checks=100000 -rapid.steps=200 -run "TestFSOps" -v -failfast -count=1 -timeout=30m -cover -coverpkg=./pkg/...,./cmd/... -args -test.gocoverdir="/home/runner/work/juicefs/juicefs/cover"
warning: no packages being tested depend on matches for pattern ./cmd/...
	github.com/juicedata/juicefs/pkg/meta/pb		coverage: 0.0% of statements
=== RUN   TestFSOps
    random_test.go:2159: [rapid] failed after 0 tests: expect [] but got []
        To reproduce, specify -run="TestFSOps" -rapid.failfile="testdata/rapid/TestFSOps/TestFSOps-2025021903[11](https://github.com/juicedata/juicefs/actions/runs/13404626272/job/37442216353#step:6:12)10-3927.fail" (or -rapid.seed=7908)
        Failed test output:
    random_test.go:[12](https://github.com/juicedata/juicefs/actions/runs/13404626272/job/37442216353#step:6:13)6: [rapid] draw sid: 0x0
    random_test.go:2159: [rapid] draw action: "Flock"
    random_test.go:163: [rapid] draw uid: 0x0
    random_test.go:164: [rapid] draw gid: 0x0
    random_test.go:176: [rapid] draw node: 0x1
    random_test.go:1928: [rapid] draw owner: 0x0
    random_test.go:1929: [rapid] draw typ: 0x0
    random_test.go:1971: expect [] but got []
--- FAIL: TestFSOps (1.05s)
FAIL
coverage: 4.3% of statements in ./pkg/..., ./cmd/...
FAIL	github.com/juicedata/juicefs/pkg/meta	1.410s

```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

### PR DESCRIPTION
**Pull request by zhijian-pro**
close #5679
close #5659

### CODE REVIEW

File: pkg/meta/random_test.go [hunk 1]
```diff
@@ -136,6 +136,7 @@ func (m *fsMachine) Init(t *rapid.T) {
 	}
 	_ = os.Remove(settingPath)
 	m.meta = NewClient(metaURL, testConfig())
+	m.meta.Reset()
```
Comment (jiefenghuang) [inline pkg/meta/random_test.go:139]: remove

File: pkg/meta/random_test.go [hunk 2]
```diff
@@ -1386,7 +1398,7 @@ func cleanupSlices(ss []tSlice) []tSlice {
 func (m *fsMachine) SetXAttr(t *rapid.T) {
 	inode := m.pickNode(t)
 	name := rapid.StringN(1, 200, XATTR_NAME_MAX+1).Draw(t, "name")
-	value := rapid.SliceOfN(rapid.Byte(), 0, XATTR_SIZE_MAX+1).Draw(t, "value")
+	value := rapid.SliceOfN(rapid.Byte(), 1, XATTR_SIZE_MAX+1).Draw(t, "value")
```
Comment (jiefenghuang) [inline pkg/meta/random_test.go:1401]: 0

File: pkg/meta/random_test.go [hunk 3]
```diff
@@ -1926,11 +1938,11 @@ func (m *fsMachine) flock(inode Ino, owner uint64, typ uint32) syscall.Errno {
 func (m *fsMachine) Flock(t *rapid.T) {
 	inode := m.pickNode(t)
 	owner := rapid.Uint64().Draw(t, "owner")
-	typ := rapid.Uint32Range(0, 3).Draw(t, "typ")
+	typ := rapid.Uint32Range(1, 2).Draw(t, "typ")
```
Comment (jiefenghuang) [inline pkg/meta/random_test.go:1941]: (0,2)

File: pkg/meta/random_test.go (hunk 1 above)
Comment (zhijian-pro) [reply pkg/meta/random_test.go:143]: This is very useful during debugging random tests, because when the last test was manually terminated, there were leftover files in the database.

File: .github/workflows/unit-random-tests.yml [hunk 4]
```diff
@@ -59,11 +61,22 @@ jobs:
...
 
       - name: Test
-        timeout-minutes: 30
+        timeout-minutes: 60
         run: |
           source .github/scripts/start_meta_engine.sh
           meta_url=$(get_meta_url ${{matrix.meta}})
-          make unit-random-test seed=$RANDOM checks=100000 steps=200 meta=$meta_url
+          number=10000
+          if [[ ${{matrix.meta}} == "tikv" ]]; then
```
Comment (jiefenghuang) [inline .github/workflows/unit-random-tests.yml:69]: This CI can be changed to a daily task, and PRs only run unit tests.

File: pkg/meta/random_test.go [hunk 5]
```diff
@@ -144,6 +150,20 @@ func (m *fsMachine) Init(t *rapid.T) {
...
+	switch m.meta.(type) {
+	case *dbMeta:
+		metaType = "db"
+	case *redisMeta:
+		metaType = "redis"
+	case tkvClient:
+		metaType = "kv"
+	}
+
+	tCounter++
```
Comment (jiefenghuang) [inline pkg/meta/random_test.go:163]: only for debug?

File: pkg/meta/random_test.go [hunk 6]
```diff
@@ -426,24 +447,33 @@ func (m *fsMachine) unlink(parent Ino, name string) syscall.Errno {
...
-	if _, ok := p.children[name]; !ok {
-		return syscall.ENOENT
-	}
-	if fsnodes_namecheck(name) != 0 {
-		return syscall.EINVAL
+	if p._type != TypeDirectory {
+		return syscall.ENOTDIR
 	}
 
+	if metaType == "db" {
```
Comment (jiefenghuang) [inline pkg/meta/random_test.go:454]: add a TODO comment? removed in future?

File: pkg/meta/random_test.go (hunk 5 above)
Comment (zhijian-pro) [reply pkg/meta/random_test.go:163]: Yes, can determine whether it is running

File: .github/workflows/unit-random-tests.yml (hunk 4 above)
Comment (zhijian-pro) [reply .github/workflows/unit-random-tests.yml:69]: The situation is as it is now

File: pkg/meta/redis.go [hunk 7]
```diff
@@ -1589,6 +1589,9 @@ func (m *redisMeta) doRmdir(ctx Context, parent Ino, name string, pinode *Ino, s
 				err = nil
 			}
 		}
+		if errors.Is(err, redis.Nil) {
```
Comment (SandyXSD) [inline pkg/meta/redis.go:1592]: Not needed.

File: pkg/meta/sql_lock.go [hunk 8]
```diff
@@ -25,15 +25,14 @@ import (
...
-
 	"xorm.io/xorm"
 )
 
 func (m *dbMeta) Flock(ctx Context, inode Ino, owner_ uint64, ltype uint32, block bool) syscall.Errno {
 	owner := int64(owner_)
 	if ltype == F_UNLCK {
 		return errno(m.txn(func(s *xorm.Session) error {
-			_, err := s.Delete(&flock{Inode: inode, Owner: owner, Sid: m.sid})
+			_, err := s.Where("inode = ? and owner = ? and sid = ?", inode, owner, m.sid).Delete(&flock{})
```
Comment (SandyXSD) [inline pkg/meta/sql_lock.go:35]: Use `MustCols`

File: pkg/meta/random_test.go [hunk 9]
```diff
@@ -2144,6 +2243,8 @@ var metaURL string
 
 func init() {
 	flag.StringVar(&metaURL, "rapid.meta", "memkv://jfs-unit-test", "meta URL")
+	// flag.StringVar(&metaURL, "rapid.meta", "sqlite3://test.db", "meta URL")
```
Comment (davies) [inline pkg/meta/random_test.go:2246]: revert
