### PR TITLE
pkg/object: fix pool buffer race in chunkedEncrypted

### LINKED ISSUE #6952: sync: After two rounds of encryption and decryption, the synced data is incorrect.
**What happened**:
https://github.com/juicedata/juicefs/actions/runs/24868673956/job/72810280150

test case: 

```
test_sync_reencrypt_cluster(){
    prepare_test
    ./juicefs mount -d $META_URL /jfs
    mkdir -p /jfs/data
    for i in $(seq 1 30); do
        dd if=/dev/urandom of=/jfs/data/file$i bs=1K count=$((RANDOM % 256 + 1)) status=none
    done
    chmod -R 777 /jfs/data

    (./mc rb myminio/reenc1 > /dev/null 2>&1 --force || true) && ./mc mb myminio/reenc1
    (./mc rb myminio/reenc2 > /dev/null 2>&1 --force || true) && ./mc mb myminio/reenc2

    # Encrypt with key1
    sudo -u juicedata meta_url=$META_URL ./juicefs sync -v jfs://meta_url/data/ minio://minioadmin:minioadmin@172.20.0.1:9000/reenc1/ \
        --encrypt-rsa-key /tmp/sync-enc-nopass.pem \
        --manager-addr 172.20.0.1:8081 --worker juicedata@172.20.0.2,juicedata@172.20.0.3 \
        --list-threads 10 --list-depth 5 \
        >sync.log 2>&1
    grep "panic:\|<FATAL>" sync.log && echo "panic or fatal" && exit 1 || true

    # Re-encrypt: key1 -> key2
    sudo -u juicedata ./juicefs sync -v minio://minioadmin:minioadmin@172.20.0.1:9000/reenc1/ minio://minioadmin:minioadmin@172.20.0.1:9000/reenc2/ \
        --decrypt-rsa-key /tmp/sync-enc-nopass.pem --encrypt-rsa-key /tmp/sync-enc-wrong.pem \
        --manager-addr 172.20.0.1:8081 --worker juicedata@172.20.0.2,juicedata@172.20.0.3 \
        --list-threads 10 --list-depth 5 \
        >sync.log 2>&1
    grep "panic:\|<FATAL>" sync.log && echo "panic or fatal" && exit 1 || true

    # Decrypt with key2 and verify
    chmod 777 /jfs
    sudo -u juicedata meta_url=$META_URL ./juicefs sync -v minio://minioadmin:minioadmin@172.20.0.1:9000/reenc2/ jfs://meta_url/decdata/ \
        --decrypt-rsa-key /tmp/sync-enc-wrong.pem \
        --manager-addr 172.20.0.1:8081 --worker juicedata@172.20.0.2,juicedata@172.20.0.3 \
        --list-threads 10 --list-depth 5 \
        >sync.log 2>&1
    cat sync.log
    grep "panic:\|<FATAL>" sync.log && echo "panic or fatal" && exit 1 || true

    diff /jfs/data/ /jfs/decdata/ || (echo "FAIL: reencrypt cluster data mismatch" && exit 1)
    echo "test_sync_reencrypt_cluster passed"
}
```
Binary files /jfs/data/file5 and /jfs/decdata/file5 differ
FAIL: reencrypt cluster data mismatch
test_sync_reencrypt_cluster exit with 1 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

### PR DESCRIPTION
**Pull request by zxh326**
close: https://github.com/juicedata/juicefs/issues/6952

### CODE REVIEW

File: pkg/object/encrypt_chunked.go [hunk 1]
```diff
@@ -162,7 +162,7 @@ func (r *chunkDecryptReader) Read(p []byte) (int, error) {
 
 	n = copy(p, plain)
 	if n < len(plain) {
-		r.buf = plain[n:]
+		r.buf = append([]byte(nil), plain[n:]...)
```
Comment (jiefenghuang) [inline pkg/object/encrypt_chunked.go]: 可以不用重新申请, 本次不释放r.pool.Put(chunkBuf), 下一次buf读完再释放

**Review by jiefenghuang — APPROVED** [review]
