### PR TITLE
fix: fuse unmount when exit

### LINKED ISSUE #5048: [MacOS] "device not configured"
**What happened**:

Running juicefs bench on macos with a default s3 + redis setup causes 

2024/08/01 23:58:22.065604 juicefs[1221] <FATAL>: Failed to open file /Volumes/datasets/__juicefs_benchmark_1722581901987909000__/bigfile.0.0: open /Volumes/datasets/__juicefs_benchmark_1722581901987909000__/bigfile.0.0: device not configured [bench.go:121]

**How to reproduce it (as minimally and precisely as possible)**:

Setup a new juicefs volume using s3 + redis

```sh
juicefs format \
          --storage s3 \
          --trash-days 7 \
          --bucket xxxx \
          --access-key xxxx \
          --secret-key xxx \
          "redis://xxx:xxxx@redis-10710.c113.us-west-2-mz.ec2.redns.redis-cloud.com:10710" \
          datasets
```

Mount it using

```
sudo juicefs mount --backup-meta 0 -d "redis://xxxx:xxxxxx@redis-10710.c113.us-west-2-mz.ec2.redns.redis-cloud.com:10710" /Volumes/datasets
```

Run `juicefs bench /Volumes/datasets/`

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: juicefs version 1.2.0+2024-06-18.873c47b922ba
- Cloud provider or hardware configuration running JuiceFS: local laptop
- OS (e.g `cat /etc/os-release`): macos 14.5 (23F79)
- Kernel (e.g. `uname -a`): Darwin Erics-MacBook-Pro.local 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000 arm64
- Object storage (cloud provider and region, or self maintained): aws s2 us-west-2
- Metadata engine info (version, cloud provider managed or self maintained): redis labs managed redis
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): JuiceFS to object storage
- Others: Macfuse version 4.8.0

### PR DESCRIPTION
**Pull request by jiefenghuang**
close #5048

### CODE REVIEW

File: pkg/fuse/fuse.go [hunk 1]
```diff
@@ -500,6 +500,7 @@ func Serve(v *vfs.VFS, options string, xattrs, ioctl bool) error {
 		}
 		return fmt.Errorf("fuse: %s", err)
 	}
+	defer fssrv.Unmount()
```
Comment (davies) [inline pkg/fuse/fuse.go:503]: This may break upgrade, which should NOT call umount before exit

Comment (jiefenghuang) [reply pkg/fuse/fuse.go:503]: upgrade call os.Exit(1) in installHandler, and wont run this defer function

**Review by zhijian-pro — APPROVED** [review]
