### PR TITLE
fix zero cache size .config display

### LINKED ISSUE #2685: check parameter consistency for cache.
**What happened**:
for example, if cache-size is 0 and upload-delay is set to 60, the upload delay will not take effect.

./juicefs-1.0.0 mount -d redis://localhost/1 /tmp/sync-test/ --log ~/.juicefs/juicefs.log --enable-xattr --attr-cache 10 --entry-cache 3 --dir-entry-cache 5 --get-timeout 54 --put-timeout 39 --io-retries 8 --max-uploads 100 --max-deletes 1 --buffer-size 215 --upload-limit 660 --download-limit 48 --prefetch 6 --writeback --upload-delay 60  --cache-size 0 --free-space-ratio 0.4436735639188675 --cache-partial-only --backup-meta 3493 --heartbeat 8 --open-cache 94 --metrics 127.0.0.1:9568 --consul 127.0.0.1:8501 --debug

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

### PR DESCRIPTION
**Pull request by zhijian-pro**
close #2685

### CODE REVIEW

File: cmd/mount.go [hunk 1]
```diff
@@ -505,6 +505,28 @@ func updateFstab(c *cli.Context) error {
 	return os.Rename(tempFstab, fstab)
 }
 
+func checkFlags(c *cli.Context) error {
```
Comment (SandyXSD) [inline cmd/mount.go:508]: Do it in `getChunkConf`

File: cmd/mount.go [hunk 2]
```diff
@@ -505,6 +508,28 @@ func updateFstab(c *cli.Context) error {
...
+	if !c.Bool("writeback") && c.IsSet("upload-delay") {
```
Comment (davies) [inline cmd/mount.go:512]: writeback can be changed, move this to the bottom

File: cmd/mount.go [hunk 3]
```diff
@@ -505,6 +508,28 @@ func updateFstab(c *cli.Context) error {
...
+	}
+	if c.Int64("cache-size") == 0 {
+		logger.Warnf("cache-size is 0, writeback and prefetch will be disable")
+		if err := c.Set("writeback", "false"); err != nil {
+			return fmt.Errorf("reset writeback: %s", err)
+		}
+		if err := c.Set("prefetch", "0"); err != nil {
+			return fmt.Errorf("reset prefetch: %s", err)
+		}
+		if err := c.Set("cache-dir", ""); err != nil {
```
Comment (davies) [inline cmd/mount.go:526]: why not "memory"?
