### PR TITLE
sync: delay deleting directories to avoid deleting empty directories

### LINKED ISSUE #5698: Some empty directories will be leaked after sync
sync tries to remove a directory before removing all the children, will fail with ENOTEMPTY and be leaked.

### PR DESCRIPTION
**Pull request by zhijian-pro**
close #5698

### CODE REVIEW

File: pkg/sync/sync.go [hunk 1]
```diff
@@ -933,7 +936,11 @@ func handleExtraObject(tasks chan<- object.Object, dstobj object.Object, config
 		return false
 	}
 	config.Limit--
-	tasks <- &withSize{dstobj, markDeleteDst}
+	if dstobj.IsDir() {
+		dstDelayDel = append(dstDelayDel, dstobj.Key())
```
Comment (davies) [inline pkg/sync/sync.go:940]: not thread safe

File: pkg/sync/sync.go [hunk 2]
```diff
@@ -1628,6 +1639,22 @@ func Sync(src, dst object.ObjectStorage, config *Config) error {
 		}()
 	}
 
+	delayDelFunc := func(storage object.ObjectStorage, keys []string) {
+		for i := len(keys) - 1; i >= 0; i-- {
```
Comment (davies) [inline pkg/sync/sync.go:1643]: add a logging if keys is not empty
