### PR TITLE
cmd/fsck: returns non-zero status code if there's error occurred during the fsck

### LINKED ISSUE #3154: Respect the result of repair
`Check` returns 0 even if it fails to repair the node, see: https://github.com/juicedata/juicefs/actions/runs/3844692510/jobs/6548964413#step:7:1022

### PR DESCRIPTION
**Pull request by SandyXSD**
close #3154

### CODE REVIEW

File: pkg/meta/base.go [hunk 1]
```diff
@@ -1721,6 +1721,7 @@ func (m *baseMeta) Check(ctx Context, fpath string, repair bool, recursive bool,
 		attr.Parent = parent
 	}
 
+	var done = true
```
Comment (davies) [inline pkg/meta/base.go:1724]: hasError

**Review by davies — APPROVED** [review]
