### PR TITLE
split insert batch

### LINKED ISSUE #1820: bad connection when load 4M empty files meta to mysql.
**What happened**:
```
2022/04/18 15:39:09.145651 juicefs[55432] <INFO>: Meta address: mysql://root:****@(localhost:3306)/load1?maxAllowedPacket=10485760 [interface.go:383]
2022/04/18 15:39:09.151272 juicefs[55432] <WARNING>: The latency to database is too high: 5.394232ms [sql.go:180]
Collected entries count: 4000940 / 4000940 [==============================================================]  done
Collected entries count: 4000940 / 4000940 [==============================================================]  done
Collected entries count: 4000940 / 4000940 [==============================================================]  done
   Loaded entries count: 268945 / 4000940 [===>----------------------------------------------------------]   7 % 21m7s
[mysql] 2022/04/18 15:41:07 connection.go:173: packet for query is too large. Try adjusting the ‘max_allowed_packet’ variable on the server
2022-04-18 15:41:07.046401 I | driver: bad connection
```

**What you expected to happen**:
succeed.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

### PR DESCRIPTION
**Pull request by zhijian-pro**
Close #1820 #1819 #1816

### CODE REVIEW

File: pkg/meta/sql.go [hunk 1]
```diff
@@ -2684,16 +2677,22 @@ func (m *dbMeta) loadEntry(e *DumpedEntry, cs *DumpedCounters, refs map[uint64]*
...
-		beans = append(beans, xattrs)
 	}
-	beans = append(beans, n)
-	s := m.db.NewSession()
-	defer s.Close()
-	return mustInsert(s, beans...)
+	beans.add(n)
+}
+
+type safeBeanSlice struct {
```
Comment (davies) [inline pkg/meta/sql.go:2687]: A channel should be enough

**Review by davies — APPROVED** [review]
