### PR TITLE
windows: fix rename bugs

### LINKED ISSUE #5871: windows: An io error occurred while changing the case of directory rename
**What happened**:
Change the directory name T to t:

Image

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

### PR DESCRIPTION
**Pull request by chenjie4255**
fix #5871 

This PR adjusts the following behaviors:

* Fixed a crash issue on Windows when renaming a.txt to A.TXT. The crash was caused by the original line 1736. see comment.
* After fixing the crash, it also fixed the issue where renaming had no effect (because the code returned early when ino == dino).
* Fixed a problem where the file name became all uppercase after renaming in File Explorer. (Solved by implementing the getpath interface.)
* Adjusted the original --access-log feature: instead of logging from the FS layer, it now logs from the WinFS layer.
* Added a case-sensitive parameter. (It is disabled by default, and can be enabled when needed.)

## Known issue:

* When case-sensitive is enabled, renaming a file to a similar name with different casing (e.g., a.txt → A.TXT) will cause the file to disappear in File Explorer. The notification sent from the WinFSP kernel contains both the old and new filenames correctly. The reason for the disappearance is currently unknown.

---

## updates 1:

* Setting windows registry hklm\system\currentcontrolset\sessionmanager\kernel\obcaseinsensitive=0 didn't help with the known issue

### CODE REVIEW

File: cmd/mount_windows.go [hunk 1]
```diff
@@ -64,6 +64,10 @@ func mountFlags() []cli.Flag {
 			Name:  "show-dot-files",
 			Usage: "If set, dot files will not be treated as hidden files",
 		},
+		&cli.BoolFlag{
+			Name:  "case-sensitive",
```
Comment (davies) [inline cmd/mount_windows.go:68]: It's known to be broken, let's hide it

File: pkg/winfsp/winfs.go [hunk 2]
```diff
@@ -727,7 +727,29 @@ func (j *juice) Chflags(path string, flags uint32) (e int) {
...
+		}
+		ino = fi.Inode()
+	}
+
+	paths := j.vfs.Meta.GetPaths(ctx, ino)
+	if len(paths) == 0 {
+		ret = p
+		return
+	}
+	ret = path.Join(paths...)
```
Comment (davies) [inline pkg/winfsp/winfs.go:748]: We should return one of them.

Multiple path is used for hardlink

File: cmd/mount_windows.go [hunk 3]
```diff
@@ -91,8 +95,12 @@ func getDaemonStage() int {
 }
 
 func mountMain(v *vfs.VFS, c *cli.Context) {
-	v.Conf.AccessLog = c.String("access-log")
-	winfsp.Serve(v, c.String("o"), c.Float64("file-cache-to"), c.Bool("as-root"), c.Int("delay-close"), c.Bool("show-dot-files"))
+	acLog := c.String("access-log")
+	if acLog != "" {
+		winfsp.SetTraceOutput(acLog)
```
Comment (davies) [inline cmd/mount_windows.go:100]: the format of tracer is different than the access log in linux, should we use another name?

File: pkg/winfsp/winfs.go (hunk 2 above)
Comment (chenjie4255) [reply pkg/winfsp/winfs.go]: ok, I see. I thought they were the splited parts. added additional codes to choose the correct one.

File: cmd/mount_windows.go (hunk 3 above)
Comment (chenjie4255) [reply cmd/mount_windows.go]: The gateway also uses the "access-log". but indeed it is better to rename it. I think the "fuse-trace-log" should be a 
 accurate one.

File: pkg/meta/redis.go [hunk 4]
```diff
@@ -1760,7 +1762,11 @@ func (m *redisMeta) doRename(ctx Context, parentSrc Ino, nameSrc string, parentD
 		}
 		if dino > 0 {
 			if ino == dino {
-				return errno(nil)
+				if m.conf.CaseInsensi && nameSrc != nameDst {
```
Comment (davies) [inline pkg/meta/redis.go:1765]: please update the sql.go and tkv.go as well

Comment (chenjie4255) [reply pkg/meta/redis.go]: This has been updated, and the original logic has been simplified. 

The #5871 has been re-verfied on both SQL and redis engine.
