### PR TITLE
meta: force compaction when there's too many slices in one chunk

### LINKED ISSUE #4536: FoundationDB error code 2103 (Value length exceeds limit)
**What happened**:
vdbench.conf:
```
data_errors=1
fsd=fsd1,anchor=/tmp/jfs,depth=1,width=2,files=2,sizes=(30m,0),shared=yes,openflags=o_direct
fwd=fwd1,fsd=fsd1,threads=4,xfersize=(512,20,4k,20,64k,20,512k,20,1024k,20),fileio=random,fileselect=random,rdpct=70
rd=rd1,fwd=fwd*,fwdrate=max,format=restart,elapsed=800,interval=1
```

Run: vdbench/vdbench -f .github/workflows/resources/vdbench_long_run.conf -jn

Log:
```

2024/03/18 09:35:39.942048 juicefs[2419] <INFO>: Meta address: fdb:///home/runner/fdb.cluster?prefix=jfs [interface.go:533]
2024/03/18 09:35:39.945[6](https://github.com/juicedata/juicefs/actions/runs/8324275602/job/22775532195#step:11:7)8[7](https://github.com/juicedata/juicefs/actions/runs/8324275602/job/22775532195#step:11:8) juicefs[2419] <INFO>: Data use file:///home/runner/.juicefs/local/vdbench-long-run/ [mount.go:589]
2024/03/18 09:35:39.972358 juicefs[2429] <INFO>: Meta address: fdb:///home/runner/fdb.cluster?prefix=jfs [interface.go:533]
2024/03/1[8](https://github.com/juicedata/juicefs/actions/runs/8324275602/job/22775532195#step:11:9) 0[9](https://github.com/juicedata/juicefs/actions/runs/8324275602/job/22775532195#step:11:10):35:39.975919 juicefs[2429] <INFO>: Data use file:///home/runner/.juicefs/local/vdbench-long-run/ [mount.go:589]
2024/03/18 09:35:40.004057 juicefs[2438] <INFO>: Meta address: fdb:///home/runner/fdb.cluster?prefix=jfs [interface.go:533]
2024/03/18 09:35:40.007738 juicefs[2438] <INFO>: Data use file:///home/runner/.juicefs/local/vdbench-long-run/ [mount.go:589]
2024/03/18 09:35:40.007768 juicefs[2438] <INFO>: JuiceFS version 1.2.0-dev+2024-03-18.73a3953 [mount.go:612]
2024/03/18 09:35:40.008379 juicefs[2438] <INFO>: Disk cache (/home/runner/.juicefs/cache/01fa7272-6d3d-42ff-9a53-dfaace0e5ee8/): capacity ([10](https://github.com/juicedata/juicefs/actions/runs/8324275602/job/22775532195#step:11:11)24 MB), free ratio (10%), max pending pages (15) [disk_cache.go:[11](https://github.com/juicedata/juicefs/actions/runs/8324275602/job/22775532195#step:11:12)6]
2024/03/18 09:35:40.013205 juicefs[2438] <INFO>: Create session 1 OK with version: 1.2.0-dev+2024-03-18.73a3953 [base.go:513]
2024/03/18 09:35:40.015471 juicefs[2438] <INFO>: Prometheus metrics listening on [12](https://github.com/juicedata/juicefs/actions/runs/8324275602/job/22775532195#step:11:13)7.0.0.1:9567 [mount.go:[13](https://github.com/juicedata/juicefs/actions/runs/8324275602/job/22775532195#step:11:14)5]
2024/03/18 09:35:40.015780 juicefs[2438] <INFO>: Mounting volume vdbench-long-run at /tmp/jfs ... [mount_unix.go:754]
2024/03/18 09:35:40.015813 juicefs[2438] <WARNING>: setpriority: permission denied [fuse.go:434]
2024-03-18 09:35:40.078518 I | Unimplemented opcode POLL
2024/03/18 09:35:40.078958 juicefs[2429] <INFO>: watching /tmp/jfs, pid 2438 [mount_unix.go:150]
2024/03/18 09:35:48.436371 juicefs[2438] <WARNING>: GET chunks/0/0/4_6_4194304: open /home/runner/.juicefs/local/vdbench-long-run/chunks/0/0/4_6_4194304: no such file or directory; retrying [cached_store.go:672]
2024/03/18 09:35:49.436496 juicefs[2438] <WARNING>: GET chunks/0/0/13_5_4194304: open /home/runner/.juicefs/local/vdbench-long-run/chunks/0/0/13_5_4194304: no such file or directory; retrying [cached_store.go:672]
2024/03/18 09:35:50.436568 juicefs[2438] <WARNING>: GET chunks/0/0/20_5_4194304: open /home/runner/.juicefs/local/vdbench-long-run/chunks/0/0/20_5_4194304: no such file or directory; retrying [cached_store.go:672]
2024/03/18 09:35:51.436823 juicefs[2438] <WARNING>: GET chunks/0/0/13_1_4194304: open /home/runner/.juicefs/local/vdbench-long-run/chunks/0/0/13_1_4194304: no such file or directory; retrying [cached_store.go:672]
2024/03/18 09:35:52.436902 juicefs[2438] <WARNING>: GET chunks/0/0/13_0_4194304: open /home/runner/.juicefs/local/vdbench-long-run/chunks/0/0/13_0_4194304: no such file or directory; retrying [cached_store.go:672]
2024/03/18 09:35:53.437015 juicefs[2438] <WARNING>: GET chunks/0/0/16_6_4194304: open /home/runner/.juicefs/local/vdbench-long-run/chunks/0/0/16_6_4194304: no such file or directory; retrying [cached_store.go:672]
2024/03/18 09:35:54.437372 juicefs[2438] <WARNING>: GET chunks/0/0/20_3_4194304: open /home/runner/.juicefs/local/vdbench-long-run/chunks/0/0/20_3_4194304: no such file or directory; retrying [cached_store.go:672]
2024/03/18 09:35:55.437462 juicefs[2438] <WARNING>: GET chunks/0/0/20_4_4194304: open /home/runner/.juicefs/local/vdbench-long-run/chunks/0/0/20_4_4194304: no such file or directory; retrying [cached_store.go:672]
2024/03/18 09:35:56.437852 juicefs[2438] <WARNING>: GET chunks/0/0/33_0_4194304: open /home/runner/.juicefs/local/vdbench-long-run/chunks/0/0/33_0_4194304: no such file or directory; retrying [cached_store.go:672]
2024/03/18 09:35:57.438079 juicefs[2438] <WARNING>: GET chunks/0/0/33_0_4194304: open /home/runner/.juicefs/local/vdbench-long-run/chunks/0/0/33_0_4194304: no such file or directory; retrying [cached_store.go:672]
2024/03/18 09:35:58.438170 juicefs[2438] <WARNING>: GET chunks/0/0/20_4_4194304: open /home/runner/.juicefs/local/vdbench-long-run/chunks/0/0/20_4_4194304: no such file or directory; retrying [cached_store.go:672]
2024/03/18 09:35:59.482267 juicefs[2438] <WARNING>: GET chunks/0/0/87_6_4194304: open /home/runner/.juicefs/local/vdbench-long-run/chunks/0/0/87_6_4194304: no such file or directory; retrying [cached_store.go:672]
2024/03/18 09:36:00.519323 juicefs[2438] <WARNING>: GET chunks/0/0/483_7_4194304: open /home/runner/.juicefs/local/vdbench-long-run/chunks/0/0/483_7_4194304: no such file or directory; retrying [cached_store.go:672]
2024/03/18 09:36:01.519446 juicefs[2438] <WARNING>: GET chunks/0/0/701_0_4194304: open /home/runner/.juicefs/local/vdbench-long-run/chunks/0/0/701_0_4194304: no such file or directory; retrying [cached_store.go:672]
2024/03/18 09:36:02.519643 juicefs[2438] <WARNING>: GET chunks/0/1/1005_4_4194304: open /home/runner/.juicefs/local/vdbench-long-run/chunks/0/1/1005_4_4194304: no such file or directory; retrying [cached_store.go:672]
2024/03/18 09:36:54.513997 juicefs[2438] <ERROR>: error: FoundationDB error code 2103 (Value length exceeds limit)
goroutine 1007298 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/juicedata/juicefs/pkg/meta.errno({0x389d6a0, 0xc00ad98db8})
	/home/runner/work/juicefs/juicefs/pkg/meta/utils.go:123 +0xad
github.com/juicedata/juicefs/pkg/meta.(*kvMeta).Write(0xc00006bf60, {0x38d6748?, 0xc000ece0c0}, 0x5, 0x0, 0x462000, {0x4199, 0x1000, 0x0, 0x1000}, ...)
	/home/runner/work/juicefs/juicefs/pkg/meta/tkv.go:2100 +0x4b6
github.com/juicedata/juicefs/pkg/vfs.(*chunkWriter).commitThread(0xc006360b10)
	/home/runner/work/juicefs/juicefs/pkg/vfs/writer.go:203 +0x1f0
created by github.com/juicedata/juicefs/pkg/vfs.(*fileWriter).writeChunk in goroutine 1007064
	/home/runner/work/juicefs/juicefs/pkg/vfs/writer.go:272 +0x3b6 [utils.go:123]
2024/03/18 09:36:54.5[14](https://github.com/juicedata/juicefs/actions/runs/8324275602/job/22775532195#step:11:15)046 juicefs[2438] <WARNING>: write inode:5 error: input/output error [writer.go:210]
2024/03/[18](https://github.com/juicedata/juicefs/actions/runs/8324275602/job/22775532195#step:11:19) 09:36:54.514089 juicefs[2438] <ERROR>: write inode:5 indx:0  input/output error [writer.go:214]
[20](https://github.com/juicedata/juicefs/actions/runs/8324275602/job/22775532195#step:11:21)24/03/18 09:36:54.626933 juicefs[2438] <ERROR>: error: FoundationDB error code [21](https://github.com/juicedata/juicefs/actions/runs/8324275602/job/22775532195#step:11:22)03 (Value length exceeds limit)
goroutine 1007261 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.21.8/x64/src/runtime/debug/stack.go:24 +0x5e
github.com/juicedata/juicefs/pkg/meta.errno({0x389d6a0, 0xc013e8f680})
	/home/runner/work/juicefs/juicefs/pkg/meta/utils.go:1[23](https://github.com/juicedata/juicefs/actions/runs/8324275602/job/22775532195#step:11:24) +0xad
github.com/juicedata/juicefs/pkg/meta.(*kvMeta).Write(0xc00006bf60, {0x38d6748?, 0xc000ece0c0}, 0x5, 0x0, 0x1a0000, {0x41a0, 0x10000, 0x0, 0x10000}, ...)
	/home/runner/work/juicefs/juicefs/pkg/meta/tkv.go:2100 +0x4b6
github.com/juicedata/juicefs/pkg/vfs.(*chunkWriter).commitThread(0xc0066a31a0)
	/home/runner/work/juicefs/juicefs/pkg/vfs/writer.go:203 +0x1f0
created by github.com/juicedata/juicefs/pkg/vfs.(*fileWriter).writeChunk in goroutine 1006827
	/home/runner/work/juicefs/juicefs/pkg/vfs/writer.go:272 +0x3b6 [utils.go:123]
20[24](https://github.com/juicedata/juicefs/actions/runs/8324275602/job/22775532195#step:11:25)/03/18 09:36:54.6[26](https://github.com/juicedata/juicefs/actions/runs/8324275602/job/22775532195#step:11:27)976 juicefs[2438] <WARNING>: write inode:5 error: input/output error [writer.go:210]
2024/03/18 09:[36](https://github.com/juicedata/juicefs/actions/runs/8324275602/job/22775532195#step:11:37):54.626997 juicefs[24[38](https://github.com/juicedata/juicefs/actions/runs/8324275602/job/22775532195#step:11:39)] <ERROR>: write inode:5 indx:0  input/output error [writer.go:214]
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

### PR DESCRIPTION
**Pull request by SandyXSD**
fix #4536 

Known limits for value:
- MySQL: 64 KiB
- FoundationDB: 100 KB
- etcd: 1MiB

### CODE REVIEW

File: pkg/meta/tkv.go [hunk 1]
```diff
@@ -2087,15 +2087,16 @@ func (m *kvMeta) Write(ctx Context, inode Ino, indx uint32, off uint32, slice Sl
...
+		numSlices = len(val) / sliceBytes
 		return nil
 	}, inode)
 	if err == nil {
-		if needCompact {
+		m.updateParentStat(ctx, inode, attr.Parent, newLength, newSpace)
+		if numSlices%100 == 99 {
 			go m.compactChunk(inode, indx, false)
+		} else if numSlices > 350 {
+			m.compactChunk(inode, indx, true)
```
Comment (davies) [inline pkg/meta/tkv.go:2098]: forced compaction will return when there is no slices.

**Comment by davies** [comment]
we can add a unit test to write 10000 times

**Comment by SandyXSD** [comment]
The etcd is misconfigured in the CI, leading to test failure whenever it runs longer than 1 minute (caused by `AutoSyncInterval: time.Minute`).
