### PR TITLE
vfs: write control file asynchronously

### LINKED ISSUE #1739: Mount process exits when running warm up
JuiceFS version: 1.0.0-dev+2022-04-06.2026936e
On Mac with small bandwidth (~ 4MB/s), warmup failed after about 1 min (not finished), and the mount process exits with the following error:
```
2022-04-07 12:03:10.920393 I | received ENODEV (unmount request), thread exiting
2022/04/07 12:03:11.521126 juicefs[28251] <INFO>: slow request: GET chunks/0/0/542_5_4194304 (<nil>, 35.682s) [cached_store.go:672]
2022/04/07 12:03:11.547048 juicefs[28251] <INFO>: close session 14: %!s(<nil>) [base.go:241]
```

### PR DESCRIPTION
**Pull request by SandyXSD**
fix #1739

Reference: https://code.google.com/archive/p/macfuse/wikis/OPTIONS.wiki

### CODE REVIEW

File: cmd/warmup.go [hunk 1]
```diff
@@ -93,8 +95,12 @@ func sendCommand(cf *os.File, batch []string, count int, threads uint, backgroun
 		return
 	}
 	var errs = make([]byte, 1)
-	if n, err := cf.Read(errs); err != nil || n != 1 {
-		logger.Fatalf("Read message: %d %s", n, err)
+	for n, err := cf.Read(errs); err != nil || n != 1; n, err = cf.Read(errs) {
```
Comment (davies) [inline cmd/warmup.go:98]: readControl()
