### PR TITLE
 meta/quota: Fix group quota check for files created in setgid directories

### LINKED ISSUE #6774: quota: GID quota test space is not being restricted.
**What happened**:
test case:
CI: https://github.com/juicedata/juicefs/actions/runs/23472608434/job/68298424510?pr=6728

```
test_user_group_membership_quota(){
    prepare_ug_quota_test
    resolve_test_users || return 0

    if [[ "$(id -u)" != "0" ]]; then
        echo "group membership test requires root, skipping"
        return 0
    fi
    for cmd in groupadd usermod gpasswd groupdel; do
        if ! command -v "$cmd" >/dev/null 2>&1; then
            echo "$cmd not available, skipping group membership test"
            return 0
        fi
    done

    NEW_GROUP="jfs-grpmem-${RANDOM}"
    groupadd "$NEW_GROUP" || { echo "cannot create test group, skipping"; return 0; }
    NEW_GID=$(getent group "$NEW_GROUP" | cut -d: -f3)

    cleanup_group() {
        gpasswd -d "$TEST_USER_1" "$NEW_GROUP" 2>/dev/null || true
        groupdel "$NEW_GROUP" 2>/dev/null || true
    }
    trap cleanup_group RETURN

    # Add TEST_USER_1 to the new group
    usermod -aG "$NEW_GROUP" "$TEST_USER_1"

    # Set gid quota on new group
    ./juicefs quota set $META_URL --gid "$NEW_GID" --inodes 3
    sleep $((HEARTBEAT_INTERVAL+HEARTBEAT_SLEEP))

    # Create setgid directory owned by new group
    mkdir -p /jfs/grpmem
    chgrp "$NEW_GID" /jfs/grpmem
    chmod 2777 /jfs/grpmem

    # Files created in setgid dir inherit gid -> counts against NEW_GID quota
    run_as_user_cmd "$TEST_USER_1" "touch /jfs/grpmem/file1"
    sleep $DIR_QUOTA_FLUSH_INTERVAL

    # Verify file has correct gid
    file_gid=$(stat -c %g /jfs/grpmem/file1)
    [[ "$file_gid" != "$NEW_GID" ]] && echo "file in setgid dir should inherit group $NEW_GID, got $file_gid" && exit 1 || true

    run_as_user_cmd "$TEST_USER_1" "touch /jfs/grpmem/file2"
    sleep $DIR_QUOTA_FLUSH_INTERVAL

    # Third file should fail — gid quota (inodes=2) exhausted
    run_as_user_cmd "$TEST_USER_1" "touch /jfs/grpmem/file3" 2>error.log \
        && echo "gid inode quota should block file creation in setgid dir" && exit 1 || true
    grep -i "Disk quota exceeded" error.log || (echo "gid quota via setgid dir not enforced" && exit 1)

    # Remove user from group — existing file quota should not change
    gpasswd -d "$TEST_USER_1" "$NEW_GROUP" 2>/dev/null || true
    ./juicefs quota list $META_URL --gid "$NEW_GID" 2>&1 | tee grpmem_quota.log
    gid_iused=$(get_quota_table_field grpmem_quota.log "GID:$NEW_GID" 7)
    [[ "$gid_iused" != "2" ]] && echo "gid iused should remain 2 after removing user from group, got $gid_iused" && exit 1 || true

    cleanup_group
    trap - RETURN
}
```

reproduce:
```
$ touch /juicefs2/grpmem/file1
$ touch /juicefs2/grpmem/file2
$ touch /juicefs2/grpmem/file3
$
root@chaos-k8s-001:~/chenyunhui/juicefs# ./juicefs quota list redis://127.0.0.1/1
2026/03/24 15:33:22.983258 juicefs[3608319] <INFO>: Meta address: redis://127.0.0.1/1 [NewClient@interface.go:651]
2026/03/24 15:33:22.983746 juicefs[3608319] <WARNING>: AOF is not enabled, you may lose data if Redis is not shutdown properly. [checkRedisInfo@info.go:84]
2026/03/24 15:33:22.983821 juicefs[3608319] <INFO>: Ping redis latency: 29.49µs [checkServerConfig@redis.go:4339]
+---------+-----------+--------+------+-----------+-------+-------+
| Path/ID |    Size   |  Used  | Use% |   Inodes  | IUsed | IUse% |
+---------+-----------+--------+------+-----------+-------+-------+
| 1000    |   1.0 GiB |    0 B |   0% | unchanged |     0 |       |
| 1017    | unchanged | 16 KiB |      |         2 |     4 |  200% |
+---------+-----------+--------+------+-----------+-------+-------+
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

### PR DESCRIPTION
**Pull request by Xuyuchao-juice**
close https://github.com/juicedata/juicefs/issues/6774

### CODE REVIEW

File: pkg/meta/base.go [hunk 1]
```diff
@@ -1481,8 +1505,16 @@ func (m *baseMeta) Mknod(ctx Context, parent Ino, name string, _type uint8, mode
...
+	if m.getFormat().UserGroupQuota {
+		var pattr Attr
+		if st := m.GetAttr(ctx, parent, &pattr); st != 0 {
+			return st
+		}
+		checkGid, _ = applyGidInheritance(ctx, _type, pattr.Gid, pattr.Mode, 0)
+	}
 	var space, inodes int64 = align4K(0), 1
-	if err := m.checkQuota(ctx, space, inodes, ctx.Uid(), ctx.Gid(), parent); err != 0 {
+	if err := m.checkQuota(ctx, space, inodes, ctx.Uid(), checkGid, parent); err != 0 {
```
Comment (jiefenghuang) [inline pkg/meta/base.go]: move to engine txn

File: pkg/meta/base.go [hunk 2]
```diff
@@ -1499,7 +1530,6 @@ func (m *baseMeta) Mknod(ctx Context, parent Ino, name string, _type uint8, mode
 	}
 	attr.Typ = _type
 	attr.Uid = ctx.Uid()
-	attr.Gid = ctx.Gid()
```
Comment (jiefenghuang) [inline pkg/meta/base.go:1502]: 这个保留

File: pkg/meta/redis.go [hunk 3]
```diff
@@ -1437,6 +1436,10 @@ func (m *redisMeta) doMknod(ctx Context, parent Ino, name string, _type uint8, m
 		if st := m.Access(ctx, parent, MODE_MASK_W|MODE_MASK_X, &pattr); st != 0 {
 			return st
 		}
+		ihGid := m.inheritGid(ctx, _type, pattr.Gid, pattr.Mode)
```
Comment (jiefenghuang) [inline pkg/meta/redis.go]: move after m.parseAttr(a, &pattr)

**Review by jiefenghuang — APPROVED** [review]

**Review by jiefenghuang — CHANGES_REQUESTED** [review]
TODO

**Review by jiefenghuang — APPROVED** [review]
