### PR TITLE
cmd/format: ignore bucket schema

### LINKED ISSUE #2750: ignore bucket schema for product ease-of-use
### Discussed in https://github.com/juicedata/juicefs/discussions/2733

<div type='discussions-op-text'>

<sup>Originally posted by **mark-rushakoff** September 13, 2022</sup>

**What happened**:

I am using juicefs-csi-driver with Nomad, with both meta and data stores in postgres. Adding a volume was failing with a cryptic error:

> `lookup postgres on <my dns server>:53: server misbehaving`

**What you expected to happen**:

Volume created correctly.

**How to reproduce it (as minimally and precisely as possible)**:

I was using this volume definition for Nomad:

```hcl
id = "demo-jfs"
name = "demo-jfs"

type = "csi"
plugin_id = "juicefs"

capacity_min = "1MiB"
capacity_max = "10MiB"

capability {
  access_mode     = "single-node-writer"
  attachment_mode = "file-system"
}

secrets {
  name = "timestamp-demo-jfs"
  metaurl = "postgres://juicefs:juicefs@sql-server.node.consul/juicefs_meta"
  bucket = "postgres://juicefs:juicefs@sql-server.node.consul/juicefs_data"
  storage = "postgres"
}
```

I later found out that it was incorrect to have the `postgres://` scheme on the secrets.bucket value, but I had to spend a lot of time debugging before I learned that. I eventually found that 

https://github.com/juicedata/juicefs/blob/54279914e423e0c78852e8166937c3ebf54c645f/pkg/object/sql.go#L163

could simply check `strings.HasPrefix(uri, "postgres://")` before adding that prefix to the `uri`.

Alternatively, the volume could have been rejected for already containing a scheme with `storage=postgres`. Either way would have saved me quite a bit of time.

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: `docker.io/juicedata/juicefs-csi-driver:v0.17.0`
- Cloud provider or hardware configuration running JuiceFS: Locally with Nomad
</div>

### PR DESCRIPTION
**Pull request by zhijian-pro**
close #2750

### CODE REVIEW

**Review by SandyXSD — APPROVED** [review]

File: cmd/config.go [hunk 1]
```diff
@@ -150,7 +150,11 @@ func config(ctx *cli.Context) error {
 				quota = true
 			}
 		case "bucket":
-			if new := ctx.String(flag); new != format.Bucket {
+			new := ctx.String(flag)
+			if format.Storage == "tikv" || format.Storage == "etcd" || format.Storage == "mysql" || format.Storage == "postgres" {
```
Comment (davies) [inline cmd/config.go:154]: It's better to support these scheme for these backends.

**Review by davies — APPROVED** [review]
