### PR TITLE
meta/sql: fix get session

### LINKED ISSUE #2719: list sessions: Error 1146: Table 'test.jfs_session2' doesn't exist [status.go:86]
**What happened**:
chengdeMacBook-Pro:scripts chengzhou$ ././juicefs-1.0.0-beta1 format mysql://root:root@\(127.0.0.1\)/test test-volume --block-size 1 --compress lz4 --shards 0 --storage minio --capacity 0 --inodes 1048576 --trash-days 0 --bucket http://localhost:9000/test-bucket --access-key minioadmin --secret-key minioadmin --debug
2022/09/10 14:06:45.708711 juicefs[41914] <INFO>: Meta address: mysql://root@(127.0.0.1)/test
[xorm] [info]  2022/09/10 14:06:45.708941 PING DATABASE mysql
2022/09/10 14:06:45.715815 juicefs[41914] <WARNING>: The latency to database is too high: 6.873466ms
2022/09/10 14:06:45.716148 juicefs[41914] <DEBUG>: Creating minio storage at endpoint http://localhost:9000/test-bucket
2022/09/10 14:06:45.716285 juicefs[41914] <INFO>: Data use minio://localhost:9000/test-bucket/test-volume/
2022/09/10 14:06:45.905615 juicefs[41914] <INFO>: Volume is formatted as {Name:test-volume UUID:a7461981-26ca-4c87-8074-b63303c95713 Storage:minio Bucket:http://localhost:9000/test-bucket AccessKey:minioadmin SecretKey:removed BlockSize:64 Compression:lz4 Shards:0 Partitions:0 Capacity:0 Inodes:1048576 EncryptKey: TrashDays:0}
chengdeMacBook-Pro:scripts chengzhou$ ./juicefs-1.0.0 status mysql://root:root@\(127.0.0.1\)/test 
2022/09/10 14:06:53.016719 juicefs[41916] <INFO>: Meta address: mysql://root:****@(127.0.0.1)/test [interface.go:402]
2022/09/10 14:06:53.023364 juicefs[41916] <WARNING>: The latency to database is too high: 6.27329ms [sql.go:203]
2022/09/10 14:06:53.028408 juicefs[41916] <FATAL>: list sessions: Error 1146: Table 'test.jfs_session2' doesn't exist [status.go:86]

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

### PR DESCRIPTION
**Pull request by zhijian-pro**
close #2719

### CODE REVIEW

File: pkg/meta/sql.go [hunk 1]
```diff
@@ -504,17 +506,20 @@ func (m *dbMeta) ListSessions() ([]*Session, error) {
...
+			for i := range rows {
+				s, err := m.getSession(&rows[i], false)
+				if err != nil {
+					logger.Errorf("get session: %s", err)
+					continue
+				}
+				sessions = append(sessions, s)
+			}
+		} else {
+			if ok, e := ses.IsTableExist(&session2{}); e != nil || ok {
```
Comment (SandyXSD) [inline pkg/meta/sql.go:520]: check table before `find`

**Review by SandyXSD — APPROVED** [review]
