### PR TITLE
tier: check the status of the last valid data block

### LINKED ISSUE #6819: tier: Overwrite type mismatch after writing
**What happened**:
```
1、git clone https://github.com/juicedata/juicefs.git juicefs2
2、echo 1 >  /juicefs2/juicefs2/Makefile
3、
The info result is incorrect：
root@chaos-k8s-001:~/chenyunhui/juicefs# ./juicefs info /juicefs2/juicefs2/Makefile
/juicefs2/juicefs2/Makefile :
  inode: 4354
  files: 1
   dirs: 0
 length: 2 Bytes
   size: 4.00 KiB (4096 Bytes)
   path: /juicefs2/Makefile
   tier: 0->default
 objects:
+------------+-----------------------------+------+--------+--------+-----+
| chunkIndex |          objectName         | size | offset | length | pos |
+------------+-----------------------------+------+--------+--------+-----+
|          0 | juicefs/chunks/0/9/9248_0_2 |    2 |      0 |      2 |   0 |
|          0 |                             |    0 |      2 |   5722 |   2 |
+------------+-----------------------------+------+--------+--------+-----+
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

### PR DESCRIPTION
**Pull request by zhijian-pro**
close #6819

### CODE REVIEW

File: cmd/tier.go [hunk 1]
```diff
@@ -153,6 +153,7 @@ func setTier(ctx *cli.Context) error {
 
 	metaFunc := func(ino meta.Ino) error {
 		if eno := m.SetAttr(meta.Background(), ino, meta.SetAttrTier, 0, &meta.Attr{Tier: newTier.ID}); eno != 0 {
+			logger.Errorf("set tier for inode %d tierID:%d failed: %s", ino, newTier.ID, eno)
```
Comment (jiefenghuang) [inline cmd/tier.go]: return error，外层打印就好了
