### PR TITLE
cmd/sync: ignore invalid pattern

### LINKED ISSUE #2563: sync failed with  --exclude '[*'
**What happened**:
```
chengdeMacBook-Pro:scripts chengzhou$ ./juicefs sync --dirs /Users/chengzhou/Documents/juicefs/pkg/ juicesync_dir/ --exclude '[*'
2022/08/19 17:16:48.972118 juicefs[81913] <INFO>: Syncing from file:///Users/chengzhou/Documents/juicefs/pkg/ to file:///Users/chengzhou/Documents/juicefs2/.github/scripts/juicesync_dir/ [sync.go:617]
2022/08/19 17:16:48.973331 juicefs[81913] <FATAL>: match [* with chunk: syntax error in pattern [sync.go:802]

chengdeMacBook-Pro:scripts chengzhou$ touch /Users/chengzhou/Documents/juicefs/pkg/[abc
chengdeMacBook-Pro:scripts chengzhou$ ls /Users/chengzhou/Documents/juicefs/pkg/ 
[abc		compress	fuse		meta		object		usage		version		winfsp
chunk		fs		gateway		metric		sync		utils		vfs


chengdeMacBook-Pro:scripts chengzhou$ ./juicefs sync --dirs /Users/chengzhou/Documents/juicefs/pkg/ juicesync_dir/ --exclude '\[*'
2022/08/19 17:26:34.071457 juicefs[82010] <INFO>: Syncing from file:///Users/chengzhou/Documents/juicefs/pkg/ to file:///Users/chengzhou/Documents/juicefs2/.github/scripts/juicesync_dir/ [sync.go:617]
Scanned objects count: 194 / 194 [==============================================================]  done      
 Copied objects count: 0                             
 Copied objects bytes: 0.00 b (0 Bytes)   0.00 b/s   
Checked objects bytes: 0.00 b (0 Bytes)   0.00 b/s   
Deleted objects count: 0                             
Skipped objects count: 194                           
 Failed objects count: 0                             
2022/08/19 17:26:34.076484 juicefs[82010] <INFO>: Found: 194, copied: 0 (0 B), checked: 0 B, deleted: 0, skipped: 194, failed: 0 [sync.go:881]
chengdeMacBook-Pro:scripts chengzhou$ ls juicesync_dir/
chunk		fs		gateway		metric		sync		utils		vfs
compress	fuse		meta		object		usage		version		winfsp

chengdeMacBook-Pro:scripts chengzhou$ rm -rf rsync_dir/ 
chengdeMacBook-Pro:scripts chengzhou$ rsync -a -r /Users/chengzhou/Documents/juicefs/pkg/ rsync_dir/ --exclude '\[*'
chengdeMacBook-Pro:scripts chengzhou$ ls rsync_dir/
chunk		fs		gateway		metric		sync		utils		vfs
compress	fuse		meta		object		usage		version		winfsp

chengdeMacBook-Pro:scripts chengzhou$ rm -rf rsync_dir/ 
chengdeMacBook-Pro:scripts chengzhou$ rsync -a -r /Users/chengzhou/Documents/juicefs/pkg/ rsync_dir/ --exclude '[*'
chengdeMacBook-Pro:scripts chengzhou$ ls rsync_dir/
[abc		compress	fuse		meta		object		usage		version		winfsp
chunk		fs		gateway		metric		sync		utils		vfs

```

**What you expected to happen**:
1. ./juicefs sync --dirs /Users/chengzhou/Documents/juicefs/pkg/ juicesync_dir/ --exclude '[*'  failed but rsync succeed with same exclude options.
2. ./juicefs sync --dirs /Users/chengzhou/Documents/juicefs/pkg/ juicesync_dir/ --exclude '\[*'  succeed and exclude file '[abc'
3. rsync -a -r /Users/chengzhou/Documents/juicefs/pkg/ rsync_dir/ --exclude '\[*' also succeed and exclude file '[abc'
4. rsync -a -r /Users/chengzhou/Documents/juicefs/pkg/ rsync_dir/ --exclude '[*' succeed but did not exclude file '[abc'

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

### PR DESCRIPTION
**Pull request by zhijian-pro**
close #2563

### CODE REVIEW

File: pkg/sync/sync.go [hunk 1]
```diff
@@ -650,8 +650,21 @@ func startProducer(tasks chan<- object.Object, src, dst object.ObjectStorage, co
 				r.pattern = strings.Replace(r.pattern, "\\", "/", -1)
 			}
 		}
-		srckeys = filter(srckeys, rules)
-		dstkeys = filter(dstkeys, rules)
+		for i := 0; i < len(rules); i++ {
+			if _, err := path.Match(rules[i].pattern, "xxxx"); err != nil {
```
Comment (davies) [inline pkg/sync/sync.go:654]: we could move this into `parseIncludeRules`
