### PR TITLE
init metrics before creating cache manager

### LINKED ISSUE #2418: CI: flaky test failure of nil pointer of prometheus vec
```
=== RUN   TestStoreAsync
2022/07/28 09:57:26.664273 juicefs[19487] <INFO>: Disk cache (/tmp/diskCache/): capacity (1 MB), free ratio (10%), max pending pages (2) [disk_cache.go:93]
2022/07/28 09:57:26.664572 juicefs[19487] <INFO>: Found 1 staging blocks (0 bytes) in /tmp/diskCache/ with 58.686µs [disk_cache.go:547]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x16899bd]
goroutine 107 [running]:
github.com/prometheus/client_golang/prometheus.(*CounterVec).WithLabelValues(0x3eef078ac16d25d1, {0xc00052a3f0, 0x1e78665, 0x22a1ee0})
	/home/travis/gopath/pkg/mod/github.com/prometheus/client_golang@v1.11.0/prometheus/counter.go:246 +0x1d
github.com/juicedata/juicefs/pkg/chunk.(*cachedStore).put.func1()
	/home/travis/gopath/src/github.com/juicedata/juicefs/pkg/chunk/cached_store.go:351 +0x451
github.com/juicedata/juicefs/pkg/utils.WithTimeout.func1()
	/home/travis/gopath/src/github.com/juicedata/juicefs/pkg/utils/utils.go:70 +0x2f
created by github.com/juicedata/juicefs/pkg/utils.WithTimeout
	/home/travis/gopath/src/github.com/juicedata/juicefs/pkg/utils/utils.go:69 +0xe5
FAIL	github.com/juicedata/juicefs/pkg/chunk	2.595s
```
https://app.travis-ci.com/github/juicedata/juicefs/builds/253736389

### PR DESCRIPTION
**Pull request by davies**
Once the cache manager is created, it may find staging blocks and start to upload them, which will crash if the metrics is not initialized.

close #2418

### CODE REVIEW

File: pkg/chunk/cached_store.go [hunk 1]
```diff
@@ -711,7 +712,11 @@ func NewCachedStore(storage object.ObjectStorage, config Config, reg prometheus.
 			}
 		}()
 	}
+	store.regMetrics(reg)
```
Comment (SandyXSD) [inline pkg/chunk/cached_store.go:715]: Why not put it right after `initMetrics`?

Comment (davies) [reply pkg/chunk/cached_store.go:715]: it depends on bcache

**Review by SandyXSD — APPROVED** [review]
