### PR TITLE
meta/tkv: fix value of delSliceKey

### LINKED ISSUE #2053: delete slice key is wrong
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

In tkv.go,  delete slice is wrong,   

delete slice key is Lcccccccctttttttt , but when set delete slice , it is set Lttttttttcccccccc.

func (m *kvMeta) delSliceKey(ts int64, chunkid uint64) []byte {
	return m.fmtKey("L",chunkid,  uint64(ts))
}

### PR DESCRIPTION
**Pull request by SandyXSD**
close #2053

### CODE REVIEW

File: pkg/meta/tkv.go [hunk 1]
```diff
@@ -1851,7 +1851,7 @@ func (m *kvMeta) doDeleteFileData(inode Ino, length uint64) {
 }
 
 func (m *kvMeta) doCleanupDelayedSlices(edge int64, limit int) (int, error) {
-	// delayed slices: Lcccccccctttttttt
+	// delayed slices: Lttttttttcccccccc
 	keys, err := m.scanKeys(m.fmtKey("L"))
```
Comment (davies) [inline pkg/meta/tkv.go:1855]: we should use scanRange to fetch only those keys we need.
