### PR TITLE
cmd/fsck: support check data by path

### LINKED ISSUE #6441: [cli] fsck --path not working as expected
cli version: 1.3.0

`fsck <metaurl>`

`fsck <metaurl> --path <path> -r`

I found that fsck with path or without path works differently. When without `--path` fsck check entire my storage and checking missing slices, but if I know which file is problematic and use `--path` to check it directly, it does not really do the job.

Is there any reason that `--path` cannot checking the missing slices? I certainly don't want to fsck entire storage every time when I just want to check a few directories.

### PR DESCRIPTION
**Pull request by simpleqin**
fsck: support check data by path

close #6441 #4994

### CODE REVIEW

File: cmd/fsck.go [hunk 1]
```diff
@@ -97,66 +111,52 @@ func fsck(ctx *cli.Context) error {
...
-	slices := make(map[meta.Ino][]meta.Slice)
-	r := m.ListSlices(c, slices, false, false, sliceCSpin.Increment)
-	if r != 0 {
-		logger.Fatalf("list all slices: %s", r)
-	}
-	sliceCSpin.Done()
-	delfilesSpin := progress.AddCountSpinner("Deleted files")
 	delfiles := make(map[meta.Ino]bool)
 	err = m.ScanDeletedObject(c, nil, nil, nil, func(ino meta.Ino, size uint64, ts int64) (clean bool, err error) {
-		delfilesSpin.Increment()
```
Comment (jiefenghuang) [inline cmd/fsck.go:143]: 这个就不需要修改了，实时更新进度

File: pkg/meta/base.go [hunk 2]
```diff
@@ -2103,7 +2104,35 @@ func (m *baseMeta) Check(ctx Context, fpath string, repair bool, recursive bool,
...
+		slices[inode] = []Slice{}
+		lock.Unlock()
+		rawSlices, st := m.en.doList(ctx, inode)
+		if st != 0 {
+			logger.Errorf("dolist %s: %s", path, st)
+			return
+		}
+		var ss []Slice
+		for _, rs := range rawSlices {
+			bs := buildSlice(rs)
```
Comment (jiefenghuang) [inline pkg/meta/base.go]: 检测原始数据，而且外层只用到id和size，buildSlice没有作用

Comment (simpleqin) [reply pkg/meta/base.go]: get

File: pkg/meta/base.go [hunk 3]
```diff
@@ -2103,7 +2104,35 @@ func (m *baseMeta) Check(ctx Context, fpath string, repair bool, recursive bool,
...
+			for _, s := range bs {
+				if s.Id == 0 {
+					continue
+				}
+				ss = append(ss, s)
+			}
+		}
+		lock.Lock()
+		slices[inode] = append(slices[inode], ss...)
+		showProgress(len(slices[inode]))
```
Comment (SandyXSD) [inline pkg/meta/base.go]: allow `showProgress` to be nil.

File: pkg/meta/redis.go [hunk 4]
```diff
@@ -2413,6 +2413,41 @@ func (m *redisMeta) doRead(ctx Context, inode Ino, indx uint32) ([]*slice, sysca
...
 }
 
+func (m *redisMeta) doList(ctx Context, inode Ino) ([][]*slice, syscall.Errno) {
+	var attr Attr
+	err := m.doGetAttr(ctx, inode, &attr)
+	if err != 0 {
+		return nil, err
+	}
+	p := m.rdb.Pipeline()
+	var slices [][]*slice
```
Comment (SandyXSD) [inline pkg/meta/redis.go]: Put all slices in a simpler `[]*slice`.

File: pkg/meta/base.go (hunk 3 above)
Comment (simpleqin) [reply pkg/meta/base.go]: ok

File: pkg/meta/redis.go (hunk 4 above)
Comment (simpleqin) [reply pkg/meta/redis.go]: ok

File: pkg/meta/base.go [hunk 5]
```diff
@@ -2120,17 +2120,16 @@ func (m *baseMeta) Check(ctx Context, fpath string, repair bool, recursive bool,
 		}
 		var ss []Slice
 		for _, rs := range rawSlices {
-			bs := buildSlice(rs)
-			for _, s := range bs {
-				if s.Id == 0 {
-					continue
-				}
-				ss = append(ss, s)
+			fmt.Println(rs)
```
Comment (SandyXSD) [inline pkg/meta/base.go]: remove this line.

File: pkg/meta/base.go [hunk 6]
```diff
@@ -2120,17 +2120,16 @@ func (m *baseMeta) Check(ctx Context, fpath string, repair bool, recursive bool,
...
+			if rs.id > 0 {
+				ss = append(ss, Slice{Id: rs.id, Size: rs.size})
 			}
 		}
 		lock.Lock()
 		slices[inode] = append(slices[inode], ss...)
```
Comment (SandyXSD) [inline pkg/meta/base.go]: `slices[inode] = ss`

File: pkg/meta/base.go [hunk 7]
```diff
@@ -2120,17 +2120,16 @@ func (m *baseMeta) Check(ctx Context, fpath string, repair bool, recursive bool,
 		}
 		var ss []Slice
```
Comment (SandyXSD) [inline pkg/meta/base.go]: `ss := make([]Slice, 0, len(rawSlices))`

File: pkg/meta/base.go (hunk 6 above)
Comment (simpleqin) [reply pkg/meta/base.go]: get

File: pkg/meta/base.go (hunk 7 above)
Comment (simpleqin) [reply pkg/meta/base.go]: get

File: pkg/meta/base.go (hunk 5 above)
Comment (simpleqin) [reply pkg/meta/base.go]: ok
