### PR TITLE
fix parse rsa from pem

### LINKED ISSUE #1708: Flaky test: TestRSA
=== RUN   TestRSA
    encrypt_test.go:56: parse without passphrase should return IncorrectPasswordError
--- FAIL: TestRSA (1.14s)

### PR DESCRIPTION
**Pull request by zhijian-pro**
Close #1708

### CODE REVIEW

File: cmd/format.go [hunk 1]
```diff
@@ -210,9 +210,12 @@ func createStorage(format meta.Format) (object.ObjectStorage, error) {
 
 	if format.EncryptKey != "" {
 		passphrase := os.Getenv("JFS_RSA_PASSPHRASE")
+		if passphrase == "" {
```
Comment (davies) [inline cmd/format.go:213]: passphrase could be '' if it's not encrypted.
