### PR TITLE
cache: force sync upload if local disk is too full for writeback

### LINKED ISSUE #942: Stop writeback when the disk is almost full
Currently, we don't limit the capacity used for writeback, which may fill all the free space, and other application may fail.

We should stop the writeback when the disk is almost full (the free ration is below half of specified `free ratio`), because writeback should have higher priority than read cache.

### PR DESCRIPTION
**Pull request by SandyXSD**
close #942

### CODE REVIEW

**Comment by SandyXSD** [comment]
An alternative is to add a flag `pauseWriteBack` and adjust it in `checkFreeSpace`, then we don't have to call `statfs` in every `stage`. What do you think? @davies

**Review by davies — CHANGES_REQUESTED** [review]
don't call statfs() for every object.

File: pkg/chunk/disk_cache.go [hunk 1]
```diff
@@ -112,7 +113,12 @@ func (cache *cacheStore) checkFreeSpace() {
 			cache.cleanup()
 			cache.Unlock()
 
-			br, fr := cache.curFreeRatio()
+			br, fr = cache.curFreeRatio()
+			if br < cache.freeRatio/2 || fr < cache.freeRatio/2 {
+				atomic.StoreInt32(&cache.pauseWB, 1)
```
Comment (davies) [inline pkg/chunk/disk_cache.go:118]: The address of cache.pauseWB should be aligned.

Since it's OK to see stale value of `pauseWB`, we don't need use atomic here.

**Review by davies — CHANGES_REQUESTED** [review]
atomic is not required

**Review by davies — APPROVED** [review]
