### PR TITLE
fix mkdir/rename/delete/rmr with trailing slash

### LINKED ISSUE #1129: gateway create or delete dir wrong
https://github.com/juicedata/juicefs/blob/e85b22f4d12c7f044a06a66f348066da0d1372f5/pkg/gateway/gateway.go#L155

this should be `sep + path.Join(p...)`, we don't need retain trailing SlashSeparator of the last element

`curl -X PUT "endpoint/bucket/path/"`  expect to create dir path, but now it will create path/path

### PR DESCRIPTION
**Pull request by davies**
Slash is a separator in JuiceFS, the trailing slash means the last component is a directory, so we can't allow upload an object with trailing slash.

close #1129

### CODE REVIEW

File: pkg/gateway/gateway.go [hunk 1]
```diff
@@ -618,11 +618,19 @@ func (n *jfsObjects) PutObject(ctx context.Context, bucket string, object string
 	}
 
 	p := n.path(bucket, object)
-	if strings.HasSuffix(object, sep) && r.Size() == 0 {
+	if strings.HasSuffix(object, sep) {
 		if err = n.mkdirAll(ctx, p, os.FileMode(0755)); err != nil {
 			err = jfsToObjectErr(ctx, err, bucket, object)
 			return
 		}
+		if r.Size() > 0 {
```
Comment (sjp00556) [inline pkg/gateway/gateway.go:626]: i think if r.Size()>0, we needn't create dir. this condition should before mkdirAll

Comment (davies) [reply pkg/gateway/gateway.go:626]: We see this behavior in MinIO, so we'd like to keep this side-affected behavior.
