### PR TITLE
meta/sql: fix mount with read-only

### LINKED ISSUE #2085: Can't mount `--read-only` with latest `main` on MySQL
**What happened**:

`<FATAL>: load setting: read-only file system [main.go:31]`

**What you expected to happen**:

Mount as read-only on passing `--read-only`

**How to reproduce it (as minimally and precisely as possible)**:

```
# juicefs mount --read-only --debug "mysql://pool:JuiceFS@(10.1.0.1:3306)/pool" /mnt/pool
2022/05/23 18:18:18.868734 juicefs[1176162] <INFO>: Meta address: mysql://pool:****@(10.1.0.1:3306)/pool [interface.go:386]
[xorm] [info]  2022/05/23 18:18:18.869263 PING DATABASE mysql
2022/05/23 18:18:18.872153 juicefs[1176162] <FATAL>: load setting: read-only file system [main.go:31]
```

**Environment**:
- JuiceFS version: `juicefs version 1.0.0-dev+2022-05-23.5dc9dd5a`

Removing `--read-only` allow mount.

### PR DESCRIPTION
**Pull request by davies**
closes #2085

### CODE REVIEW

File: pkg/meta/redis_test.go [hunk 1]
```diff
@@ -1291,6 +1291,9 @@ func testReadOnly(t *testing.T, m Meta) {
 
 	var inode Ino
 	var attr = &Attr{}
+	if st := m.GetAttr(ctx, 1, attr); st != 0 {
+		t.Fatalf("mkdir d: %s", st)
```
Comment (SandyXSD) [inline pkg/meta/redis_test.go:1295]: "getattr 1"

**Review by SandyXSD — APPROVED** [review]
