### PR TITLE
mount: recovery read only file handler

### LINKED ISSUE #4504: Unknown error 512 on try to get lock when graceful upgrade.
**What happened**:
In terminal 1:
```
root@bench-01:~/juicefs#  ./juicefs mount -d sqlite3://test.db /tmp/jfs
root@bench-01:~/juicefs# echo abc | tee /tmp/jfs/test
root@bench-01:~/juicefs# flock -x /tmp/jfs/test -c cat
```

In terminal 2:
`root@bench-01:~/juicefs# flock -s  /tmp/jfs/test -c "echo abc"`

In terminal 3:
`root@bench-01:~/juicefs#  ./juicefs mount -d sqlite3://test.db /tmp/jfs`

Terminal 2 will report flock: /tmp/jfs/test: Unknown error 512 after graceful upgrade in terminal 3.
```
root@bench-01:~/juicefs# flock -s  /tmp/jfs/test -c "echo abc"
flock: /tmp/jfs/test: Unknown error 512
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

### PR DESCRIPTION
**Pull request by zhijian-pro**
close #4504

### CODE REVIEW

File: pkg/vfs/vfs.go [hunk 1]
```diff
@@ -687,10 +699,31 @@ func (v *VFS) Read(ctx Context, ino Ino, buf []byte, off uint64, fh uint64) (n i
 		err = syscall.EBADF
 		return
 	}
+	if h.flags == 0 {
```
Comment (zhijian-pro) [inline pkg/vfs/vfs.go:702]: We need a way to determine if this `fh` is just recovered. 
flag is always equal to 0 because `syscall.O_RDONLY` is 0.

File: pkg/vfs/handle.go [hunk 2]
```diff
@@ -214,8 +232,12 @@ func (v *VFS) releaseHandle(inode Ino, fh uint64) {
 	}
 }
 
+func hasReadPerm(flag uint32) bool {
+	return (flag & O_ACCMODE) != syscall.O_WRONLY
+}
+
 func (v *VFS) newFileHandle(inode Ino, length uint64, flags uint32) uint64 {
-	h := v.newHandle(inode)
+	h := v.newHandle(inode, hasReadPerm(flags))
```
Comment (davies) [inline pkg/vfs/handle.go:240]: readOnly != hasRead

File: pkg/vfs/vfs.go [hunk 3]
```diff
@@ -695,6 +727,12 @@ func (v *VFS) Read(ctx Context, ino Ino, buf []byte, off uint64, fh uint64) (n i
 		err = syscall.EBADF
 		return
 	}
+
+	// there could be read operation for write-only if kernel writeback is enabled
+	if !v.Conf.FuseOpts.EnableWriteback && !hasReadPerm(h.flags) {
+		err = syscall.EACCES
```
Comment (davies) [inline pkg/vfs/vfs.go:733]: EBADF  fd is not a valid file descriptor or is not open for reading.
