### PR TITLE
object/webdav: replace webdav client

### LINKED ISSUE #2266: Errors on WebDAV operations, but files are created
Juicefs (1.0.0-rc1) outputs a 401, but bucket is created (folder 'jfs' is created at the root path) on server (so, credentials are OK).
Happy to provide more debug info if needed (note i have no admin access on WebdDAV server).

```
# juicefs format --storage webdav --bucket https://web.dav.server/ --access-key 307399 --secret-key tTxX12NPMyy --trash-days 0 redis://127.0.0.1:6379/1 jfs

2022/06/17 11:45:19.373300 juicefs[799909] <INFO>: Meta address: redis://127.0.0.1:6379/1 [interface.go:397]
2022/06/17 11:45:19.375116 juicefs[799909] <INFO>: Ping redis: 82.354µs [redis.go:2869]
2022/06/17 11:45:19.375437 juicefs[799909] <INFO>: Data use webdav://web.dav.server/jfs/ [format.go:420]
2022/06/17 11:45:19.529334 juicefs[799909] <WARNING>: List storage webdav://web.dav.server/jfs/ failed: 401 Unauthorized: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>401 Unauthorized</title>
</head><body>
<h1>Unauthorized</h1>
<p>This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.</p>
</body></html> [format.go:438]
2022/06/17 11:45:19.535569 juicefs[799909] <INFO>: Volume is formatted as {Name:jfs UUID:05363857-2fce-42dc-94e2-4d41c33172d0 Storage:webdav Bucket:https://web.dav.server/ AccessKey:307399 SecretKey:removed BlockSize:4096 Compression:none Shards:0 HashPrefix:false Capacity:0 Inodes:0 EncryptKey: KeyEncrypted:true TrashDays:0 MetaVersion:1 MinClientVersion: MaxClientVersion:} [format.go:458]
```
or trying to destroy it:
```
# juicefs destroy redis://127.0.0.1:6379/1 05363857-2fce-42dc-94e2-4d41c33172d0

2022/06/17 11:50:24.072353 juicefs[800639] <INFO>: Meta address: redis://127.0.0.1:6379/1 [interface.go:397]
2022/06/17 11:50:24.073182 juicefs[800639] <INFO>: Ping redis: 67.778µs [redis.go:2869]
 volume name: jfs
 volume UUID: 05363857-2fce-42dc-94e2-4d41c33172d0
data storage: webdav://web.dav.server/jfs/
  used bytes: 0
 used inodes: 0
WARNING: The target volume will be destoried permanently, including:
WARNING: 1. ALL objects in the data storage: webdav://web.dav.server/jfs/
WARNING: 2. ALL entries in the metadata engine: redis://127.0.0.1:6379/1
Proceed anyway? [y/N]: y
2022/06/17 11:50:25.693697 juicefs[800639] <FATAL>: list all objects: 401 Unauthorized: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>401 Unauthorized</title>
</head><body>
<h1>Unauthorized</h1>
<p>This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.</p>
</body></html> [destroy.go:158]
```
On files operations, files (chunks folder is populated) but this is logged:

```
2022/06/17 12:02:54.141831 juicefs[802424] <INFO>: Mounting volume jfs at /mnt/jfs ... [mount_unix.go:181]
2022/06/17 12:04:31.053268 juicefs[802424] <WARNING>: Upload chunks/0/0/7_0_140: 403 Forbidden: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access this resource.</p>
</body></html> (try 1) [cached_store.go:462]
```
Accessing WebDAV directly (outside juicefs) we can see correct file operations:
image

### PR DESCRIPTION
**Pull request by zhijian-pro**
Close #2266

### CODE REVIEW

File: pkg/object/webdav.go [hunk 1]
```diff
@@ -113,20 +170,62 @@ func (w *webdav) Copy(dst, src string) error {
 
 type WebDAVWalkFunc func(path string, info fs.FileInfo, err error) error
 
+type webDAVFile struct {
```
Comment (davies) [inline pkg/object/webdav.go:173]: type webDavFile struct {
   os.FileInfo
   name string
}

File: pkg/object/webdav.go [hunk 2]
```diff
@@ -85,103 +111,162 @@ func (w *webdav) Get(key string, off, limit int64) (io.ReadCloser, error) {
...
+		return w.c.MkdirAll(key, 0)
 	}
-	return false
+	return w.c.WriteStream(key, in, 0)
 }
 
-func (w *webdav) path(key string) string {
-	return "/" + key
+func (w *webdav) Delete(key string) error {
+	if strings.HasSuffix(key, dirSuffix) {
```
Comment (zhijian-pro) [inline pkg/object/webdav.go:143]: put  `a/b/c/d`   and then delete `a/b/c` , `a/b/c`  is a directory with files, but will be deleted.

**Review by davies — APPROVED** [review]

**Review by SandyXSD — APPROVED** [review]
