### PR TITLE
object: fix verify checksum 

### LINKED ISSUE #4210: juicefs objectstore checker bug
**What happened**:
When juicefs GetObject, it doesnot check object crc32 as expected. Detail Test as follows:
**step1**: I format a juicefs using s3 as object store and mount
"juicefs.ceph format --storage=s3 --bucket=http://XXX/test-bucket --access-key=XXX --secret-key=XXX juicefs-test"
"juicefs.ceph mount XXX /mnt/test"

**step2**: I create and write a simple file
"echo 111111 > /mnt/test/testfile "

**step3**: I use s3cmd to upload a faked file named "a" which only contain a charactor 'x' to corrupt object data and metadata of matched object in s3
 "s3cmd put a s3://test-bucket/juicefs-test/chunks/0/0/1_0_6 --add-header=x-amz-meta-Crc32c:234"

**step4**: cat /mnt/test/testfile,  I can read  faked file content which is 'x' 

**What you expected to happen**:
I expect it should return a uncompleted error when I cat the file, because data has coruppted 

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: v1.0.4
- OS (e.g `cat /etc/os-release`): ubuntu20
- Kernel (e.g. `uname -a`): Linux ubuntu 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Object storage (cloud provider and region, or self maintained): cephrgw as object store
- Metadata engine info (version, cloud provider managed or self maintained): tikv
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage): internal network , 25Gb net

### PR DESCRIPTION
**Pull request by zhijian-pro**
close #4210

### CODE REVIEW

File: pkg/object/s3.go [hunk 1]
```diff
@@ -137,7 +137,7 @@ func (s *s3client) Get(key string, off, limit int64) (io.ReadCloser, error) {
 	if off == 0 && limit == -1 {
 		cs := resp.Metadata[checksumAlgr]
 		if cs != nil {
-			resp.Body = verifyChecksum(resp.Body, *cs)
```
Comment (davies) [inline pkg/object/s3.go:140]: Can resp.ContentLength be nil?

File: pkg/object/oss.go [hunk 2]
```diff
@@ -126,8 +126,13 @@ func (o *ossClient) Get(key string, off, limit int64) (resp io.ReadCloser, err e
 	} else {
 		resp, err = o.bucket.GetObject(key, oss.GetResponseHeader(&respHeader))
 		if err == nil {
+			length, err := strconv.ParseInt(resp.(*oss.Response).Headers.Get(oss.HTTPHeaderContentLength), 10, 64)
+			if err != nil {
+				return nil, err
```
Comment (davies) [inline pkg/object/oss.go:131]: warning, don't fail

File: pkg/object/checksum.go [hunk 3]
```diff
@@ -54,20 +54,22 @@ func generateChecksum(in io.ReadSeeker) string {
...
+	checksum        uint32
+	remainingLength int64
 }
 
 func (c *checksumReader) Read(buf []byte) (n int, err error) {
 	n, err = c.ReadCloser.Read(buf)
 	c.checksum = crc32.Update(c.checksum, crc32c, buf[:n])
-	if err == io.EOF && c.checksum != c.expected {
+	c.remainingLength -= int64(n)
+	if (err == io.EOF || c.remainingLength <= 0) && c.checksum != c.expected {
```
Comment (davies) [inline pkg/object/checksum.go:66]: remainingLength == 0
