### PR TITLE
cache: fix disk cache full checking logic

### LINKED ISSUE #6247: v1.3.0 can't detect inode usage and thus disables disk cache on btrfs
**What happened**:
juicefs v1.3.0 can't detect inode usage and thus disables disk cache on `btrfs` formated drives
Example:
```
2025/07/07 21:32:17.721190 juicefs[427525] <INFO>: JuiceFS version 1.3.0+2025-07-03.30190ca [mount@mount.go:631]
2025/07/07 21:32:17.722077 juicefs[427525] <WARNING>: not enough space (27%) or inodes (0%) for caching in /var/jfsCache/d7850040-2b75-433a-8b6e-aba0f9a76da7/: free ratio should be >= 10% [newCacheStore@disk_cache.go:145]
2025/07/07 21:32:17.722159 juicefs[427525] <INFO>: Disk cache (/var/jfsCache/d7850040-2b75-433a-8b6e-aba0f9a76da7/): used ratio - [space 72.1%, inode 100%] [newCacheStore@disk_cache.go:147]
2025/07/07 21:32:17.722194 juicefs[427525] <INFO>: Adjusted max items based on freeratio: from 0 to 0 items [setlimitByFreeRatio@disk_cache.go:176]
```

**What you expected to happen**:
If it can't detect it, it should behave like the previous versions and just ignore that part of the check and just look at the free %
Example:
```
2025/07/05 21:57:06.193348 juicefs[3174815] <INFO>: JuiceFS version 1.2.3+2025-01-22.4f2aba8 [mount.go:659]
2025/07/05 21:57:06.193790 juicefs[3174815] <INFO>: Disk cache (/var/jfsCache/d7850040-2b75-433a-8b6e-aba0f9a76da7/): capacity (100 GiB), free ratio 10%, used ratio - [space 72.5%, inode NaN%], max pending pages 15 [disk_cache.go:144]
```

**How to reproduce it (as minimally and precisely as possible)**:
Format a drive or partition with btrfs and try to have the disk cache folder on it

**Anything else we need to know?**
This is not an issue on `ext4` formatted drives. I'm not sure if it affects drives other than `btrfs` as these two are the only filesystems I use.

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: 1.3.0+2025-07-03.30190ca
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`): Debian GNU/Linux 12 (bookworm)
- Kernel (e.g. `uname -a`): 6.12.12
- Object storage (cloud provider and region, or self maintained): s3
- Metadata engine info (version, cloud provider managed or self maintained): mysql
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

### PR DESCRIPTION
**Pull request by VerTiGoEtrex**
Fixes #6247

Happy to create a new source issue and copy the context. Technically, the cache is enabled, it's just stuck with no more than one item in it.

I'm running this patch locally and having no issues with it. Finally seeing some hits.

image

### CODE REVIEW

File: pkg/chunk/disk_cache.go [hunk 1]
```diff
@@ -342,15 +348,23 @@ func (cache *cacheStore) stats() (int64, int64) {
 func (cache *cacheStore) checkFreeSpace() {
 	for cache.available() {
 		usage := cache.curFreeRatio()
-		cache.stageFull = usage.br < cache.freeRatio/2 || usage.fr < cache.freeRatio/2
-		cache.rawFull = usage.br < cache.freeRatio || usage.fr < cache.freeRatio
+		hasInodeStats := usage.inodeCap > 0
```
Comment (jiefenghuang) [inline pkg/chunk/disk_cache.go]: Thanks for your feedback. The current issue should be that when checking for “full,” we need to exclude this kind of exceptional case. We can keep only this checkFreeSpace logic, and leave the rest of the logic unchanged.

File: pkg/chunk/disk_cache.go [hunk 2]
```diff
@@ -808,7 +822,8 @@ func (cache *cacheStore) cleanupFull() {
 			goal = (cache.used - toFree) * 95 / 100
 		}
 	}
-	if usage.fr < cache.freeRatio {
+	hasInodeStats := usage.inodeCap > 0
```
Comment (jiefenghuang) [inline pkg/chunk/disk_cache.go]: not needed

File: pkg/chunk/disk_cache.go [hunk 3]
```diff
@@ -169,22 +172,25 @@ func newCacheStore(m *cacheManagerMetrics, dir string, cacheSize, maxItems int64
 }
 
 func (cache *cacheStore) setLimitByFreeRatio(usage DiskFreeRatio, freeRatio float32) {
+	hasInodeStats := usage.inodeCap > 0
```
Comment (jiefenghuang) [inline pkg/chunk/disk_cache.go]: not needed

File: pkg/chunk/disk_cache.go [hunk 4]
```diff
@@ -147,7 +147,10 @@ func newCacheStore(m *cacheManagerMetrics, dir string, cacheSize, maxItems int64
 
 	c.createDir(c.dir)
 	usage := c.curFreeRatio()
-	if usage.br < c.freeRatio || usage.fr < c.freeRatio {
+	hasInodeStats := usage.inodeCap > 0
```
Comment (jiefenghuang) [inline pkg/chunk/disk_cache.go]: For this special case, it’s better to keep this warning.

File: pkg/chunk/disk_cache.go [hunk 5]
```diff
@@ -342,15 +348,23 @@ func (cache *cacheStore) stats() (int64, int64) {
 func (cache *cacheStore) checkFreeSpace() {
 	for cache.available() {
 		usage := cache.curFreeRatio()
-		cache.stageFull = usage.br < cache.freeRatio/2 || usage.fr < cache.freeRatio/2
-		cache.rawFull = usage.br < cache.freeRatio || usage.fr < cache.freeRatio
+		hasInodeStats := usage.inodeCap > 0
+		spaceStageFull := usage.br < cache.freeRatio/2
+		inodeStageFull := hasInodeStats && usage.fr < cache.freeRatio/2
+		cache.stageFull = spaceStageFull || inodeStageFull
```
Comment (jiefenghuang) [inline pkg/chunk/disk_cache.go]: cache.stageFull = usage.br < cache.freeRatio/2 || (usage.inodeCap > 0 && usage.fr < cache.freeRatio/2)

**Review by jiefenghuang — APPROVED** [review]

**Comment by Annoiiyed** [comment]
Any indication when we could expect this to be released? :)
