### PR TITLE
meta: recreate the session with info if it was cleaned before

### LINKED ISSUE #3183: Session information is not recreated after network failure recovery
**What happened**:
We injected a 5 minute network failure at a certain node. After the fault is restored, the exception below will always be reported
```
2023/01/13 15:06:57.651702 juicefs[3896811] <ERROR>: update session: no session found matching sid: 969 [sql.go:1904]
```
the sid=969 has been cleared in meta-store, but the mount client has not recreated the session.

**What you expected to happen**:
mount client can recreated the session information after Network failure recovery 

**How to reproduce it (as minimally and precisely as possible)**:
injected a 5 minute network failure to meta-store

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version: juicefs version 1.0.3+2022-12-27.e4bf15a
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

### PR DESCRIPTION
**Pull request by SandyXSD**
close #3183

### CODE REVIEW

File: pkg/meta/redis.go [hunk 1]
```diff
@@ -1932,10 +1932,21 @@ func (m *redisMeta) doFindStaleSessions(limit int) ([]uint64, error) {
 	return sids, nil
 }
 
-func (m *redisMeta) doRefreshSession() {
-	m.rdb.ZAdd(Background, m.allSessions(), &redis.Z{
+func (m *redisMeta) doRefreshSession() error {
+	ctx := Background
+	ssid := strconv.FormatUint(m.sid, 10)
+	// we have to check sessionInfo here because the operations are not within a transaction
```
Comment (davies) [inline pkg/meta/redis.go:1938]: Why not use transaction here?
