### PR TITLE
fix windows color print

### LINKED ISSUE #2558: Term Color is not supported in Windows
image

### PR DESCRIPTION
**Pull request by zhijian-pro**
Do not display colors in Windows.
close #2558

### CODE REVIEW

File: cmd/bench.go [hunk 1]
```diff
@@ -362,8 +362,8 @@ func bench(ctx *cli.Context) error {
 		fmt.Println("Cleaning kernel cache, may ask for root privilege...")
 	}
 	dropCaches()
-	bm.tty = isatty.IsTerminal(os.Stdout.Fd())
-	progress := utils.NewProgress(!bm.tty, false)
+	bm.colorful = utils.HasColorAble()
+	progress := utils.NewProgress(!isatty.IsTerminal(os.Stdout.Fd()), false)
```
Comment (SandyXSD) [inline cmd/bench.go:366]: pass `quiet = false`

File: cmd/objbench.go [hunk 2]
```diff
@@ -145,9 +145,9 @@ func objbench(ctx *cli.Context) error {
 	bCount := int(math.Ceil(float64(fsize) / float64(bSize)))
 	sCount := int(ctx.Uint("small-objects"))
 	threads := int(ctx.Uint("threads"))
-	tty := isatty.IsTerminal(os.Stdout.Fd())
-	progress := utils.NewProgress(!tty, false)
-	if tty {
+	colorful := utils.HasColorAble()
+	progress := utils.NewProgress(!isatty.IsTerminal(os.Stdout.Fd()), false)
```
Comment (SandyXSD) [inline cmd/objbench.go:149]: same here

File: pkg/utils/utils.go [hunk 3]
```diff
@@ -124,3 +127,7 @@ func FormatBytes(n uint64) string {
 	}
 	return fmt.Sprintf("%.2f %siB (%d Bytes)", float64(m)/1024.0, units[i], n)
 }
+
+func HasColorAble() bool {
```
Comment (SandyXSD) [inline pkg/utils/utils.go:131]: use `Colorable`

File: pkg/utils/utils.go [hunk 4]
```diff
@@ -124,3 +127,7 @@ func FormatBytes(n uint64) string {
 	}
 	return fmt.Sprintf("%.2f %siB (%d Bytes)", float64(m)/1024.0, units[i], n)
 }
+
+func ColorAble(fd uintptr) bool {
```
Comment (davies) [inline pkg/utils/utils.go:131]: SupportColor

File: pkg/utils/utils.go [hunk 5]
```diff
@@ -124,3 +127,7 @@ func FormatBytes(n uint64) string {
 	}
 	return fmt.Sprintf("%.2f %siB (%d Bytes)", float64(m)/1024.0, units[i], n)
 }
+
+func SupportANSIColor(fd uintptr) bool {
+	return isatty.IsTerminal(fd) && runtime.GOOS != "windows"
```
Comment (qingyunha) [inline pkg/utils/utils.go:132]: Threre are some Windows terminal support ANSI escape sequences.   
https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_ansi_terminals?view=powershell-7.2

> Since taking ownership of the Windows command-line in 2014, the team added several new features to the Console, including background transparency, line-based selection, support for [ANSI / Virtual Terminal sequences](https://en.wikipedia.org/wiki/ANSI_escape_code), [24-bit color](https://devblogs.microsoft.com/commandline/24-bit-color-in-the-windows-console/), a [Pseudoconsole ("ConPTY")](https://devblogs.microsoft.com/commandline/windows-command-line-introducing-the-windows-pseudo-console-conpty/), and more.

https://github.com/microsoft/terminal

Comment (zhijian-pro) [reply pkg/utils/utils.go:132]: Currently displaying color support in Windows is not good and the problem has a small impact, so we have turned off the feature for now in order to solve the problem faster. Maybe in the future we will fully support color display in Windows.
