### PR TITLE
meta/sql: fix retriable error message

### LINKED ISSUE #2101: Duplicate entry 'nextTrash' for key 'PRIMARY' for oceanbase meta engine
**What happened**:
https://github.com/juicedata/juicefs/runs/6602412688?check_suite_focus=true

```
+ ./juicefs sync --dirs data/ ***localhost:8080/myjfs/data/ --no-https -p 30
2022/05/26 08:47:15.227159 juicefs[2177206] <INFO>: Syncing from file:///root/actions-runner/_work/juicefs/juicefs/data/ to s3://myjfs/data/ [sync.go:619]
2022/05/26 08:47:15.228972 juicefs[2177205] <INFO>: Syncing from file:///root/actions-runner/_work/juicefs/juicefs/data/ to s3://myjfs/data/ [sync.go:619]
2022/05/26 08:47:15.232103 juicefs[2177207] <INFO>: Syncing from file:///root/actions-runner/_work/juicefs/juicefs/data/ to s3://myjfs/data/ [sync.go:619]
2022/05/26 08:47:20.239986 juicefs[2177170] <ERROR>: error: Error 1062: Duplicate entry 'nextTrash' for key 'PRIMARY'
goroutine 1756 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x65
github.com/juicedata/juicefs/pkg/meta.errno({0x3022360, 0xc0006778d8})
	/root/actions-runner/_work/juicefs/juicefs/pkg/meta/utils.go:92 +0xc5
github.com/juicedata/juicefs/pkg/meta.(*dbMeta).doMknod(0xc001a28000, {0x30bb588, 0x4b511a0}, 0x7fffffff10000000, {0xc000053f10, 0xd}, 0x2, 0x16d, 0x0, 0x0, ...)
	/root/actions-runner/_work/juicefs/juicefs/pkg/meta/sql.go:1054 +0x2b9
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).checkTrash(0xc001a28000, 0xc002816760, 0xc000053ef8)
	/root/actions-runner/_work/juicefs/juicefs/pkg/meta/base.go:917 +0x2c3
github.com/juicedata/juicefs/pkg/meta.(*dbMeta).doRename(0xc001a28000, {0x30bb5f8, 0xc0019c7ef0}, 0x1e, {0xc00279b17a, 0x24}, 0x1a, {0xc0027c19b3, 0x2}, 0x0, ...)
	/root/actions-runner/_work/juicefs/juicefs/pkg/meta/sql.go:1414 +0xa5
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).Rename(0xc001a28000, {0x30bb5f8, 0xc0019c7ef0}, 0x1e, {0xc00279b17a, 0xc0019c7ef0}, 0x1a, {0xc0027c19b3, 0xc002b14230}, 0x0, ...)
	/root/actions-runner/_work/juicefs/juicefs/pkg/meta/base.go:747 +0x31a
github.com/juicedata/juicefs/pkg/fs.(*FileSystem).Rename(0xc001998840, {0x30bb5f8, 0xc0019c7ef0}, {0xc00279b170, 0x2e}, {0xc0027c1980, 0x35}, 0x0)
	/root/actions-runner/_work/juicefs/juicefs/pkg/fs/fs.go:466 +0x595
github.com/juicedata/juicefs/pkg/gateway.(*jfsObjects).putObject(0xc001986800, {0x[307](https://github.com/juicedata/juicefs/runs/6602412688?check_suite_focus=true#step:4:321)4050, 0xc0027bb650}, {0xc0027c6485, 0xc0022ed280}, {0xc0027c1980, 0x35}, _, {{0x0, 0x0}, ...})
	/root/actions-runner/_work/juicefs/juicefs/pkg/gateway/gateway.go:636 +0x557
github.com/juicedata/juicefs/pkg/gateway.(*jfsObjects).PutObjectPart(0xc001986800, {0x3074050, 0xc0027bb650}, {_, _}, {_, _}, {_, _}, 0x31, ...)
	/root/actions-runner/_work/juicefs/juicefs/pkg/gateway/gateway.go:816 +0x24e
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

### PR DESCRIPTION
**Pull request by davies**
closes #2101

### CODE REVIEW

File: pkg/meta/sql.go [hunk 1]
```diff
@@ -611,10 +611,11 @@ func (m *dbMeta) shouldRetry(err error) bool {
 	case "mysql":
 		// MySQL, MariaDB or TiDB
 		return strings.Contains(msg, "try restarting transaction") || strings.Contains(msg, "try again later") ||
-			strings.Contains(msg, "Duplicate entry")
+			strings.Contains(msg, "duplicate entry")
```
Comment (SandyXSD) [inline pkg/meta/sql.go:614]: It is `D`, see: 
> Error 1062: Duplicate entry 'nextTrash' for key 'PRIMARY'

Comment (davies) [reply pkg/meta/sql.go:614]: we convert them into lower cases
