### PR TITLE
sync: fix match two star

### LINKED ISSUE #4451: result not correct when sync --exclude with **
**What happened**:
Test code:
```
    def test_sync6(self):
        state = SyncMachine()
        v1 = state.init_folders()
        v2 = state.create_file(content=b'', file_name='a', mode='w', parent=v1, umask=0)
        state.sync(options=[{'option': '--exclude', 'pattern': '**a'}])
        state.teardown()
```
Log:
```
root@bench-01:~/juicefs# python3 .github/scripts/hypo/syncrand_test.py -k test_sync6
setup_logger ./syncrand.log
2024-03-06 16:44:36,446 - INFO - do_create_file /tmp/sync_src/a with mode w succeed
2024-03-06 16:44:36,446 - INFO - do_create_file /tmp/sync_src2/a with mode w succeed
2024-03-06 16:44:36,448 - INFO - rsync -r -vvv /tmp/sync_src/ /tmp/rsync/ --exclude **a
2024-03-06 16:44:36,450 - INFO - ./juicefs sync --dirs -v /tmp/sync_src/ /tmp/juicesync/ --exclude **a
Only in /tmp/juicesync: a
Command '['diff', '-r', '/tmp/rsync', '/tmp/juicesync']' returned non-zero exit status 1.
E
======================================================================
ERROR: test_sync6 (__main__.TestFsrand2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File ".github/scripts/hypo/syncrand_test.py", line 50, in test_sync6
    state.sync(options=[{'option': '--exclude', 'pattern': '**a'}])
  File "/root/juicefs/.github/scripts/hypo/syncrand.py", line 104, in sync
    )
  File "/root/hypothesis/hypothesis-python/src/hypothesis/stateful.py", line 681, in rule_wrapper
    return f(*args, **kwargs)
  File "/root/juicefs/.github/scripts/hypo/syncrand.py", line 117, in sync
    raise e
  File "/root/juicefs/.github/scripts/hypo/syncrand.py", line 114, in sync
    subprocess.check_call(['diff', '-r', self.DEST_RSYNC, self.DEST_JUICESYNC])
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['diff', '-r', '/tmp/rsync', '/tmp/juicesync']' returned non-zero exit status 1.

----------------------------------------------------------------------
Ran 1 test in 0.044s

FAILED (errors=1)

root@bench-01:~/juicefs# tree /tmp/sync_src /tmp/rsync/ /tmp/juicesync/
/tmp/sync_src
└── a
/tmp/rsync/
/tmp/juicesync/
└── a
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

### PR DESCRIPTION
**Pull request by zhijian-pro**
close #4451

### CODE REVIEW

File: pkg/sync/sync.go [hunk 1]
```diff
@@ -894,7 +894,7 @@ func matchTwoStar(p string, s []string) bool {
 	if !ok {
 		return false
 	}
-	for i := 1; i <= len(s); i++ {
```
Comment (davies) [inline pkg/sync/sync.go:897]: please add the failed case

Comment (zhijian-pro) [reply pkg/sync/sync.go:897]: image
