### PR TITLE
logging into file in background mode

### LINKED ISSUE #574: Redirect stdout/stderr to a file in daemon mode
Currently, stdout and stderr are redirected to /dev/null in daemon mode, so we can't find the logging if it crashes.

### PR DESCRIPTION
**Pull request by davies**
Closes #574

### CODE REVIEW

File: cmd/mount_unix.go [hunk 1]
```diff
@@ -70,8 +71,14 @@ func makeDaemon(name, mp string) error {
 				}
 			}
 		}
+		var err error
+		logfile := c.String("logfile")
+		attrs.Stdout, err = os.OpenFile(logfile, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0755)
```
Comment (Sandy4999) [inline cmd/mount_unix.go:76]: x is not needed for logfile, use mode 0644

**Review by Sandy4999 — APPROVED** [review]
