### PR TITLE
obj/redis: support redis sentinel & cluster mode

### LINKED ISSUE #2366: Support Redis Sentinel configuration also for data storage
**What would you like to be added**:
Possibility to use Redis Sentinel configuration for data storage same as for metadata.

**Why is this needed**: 
We want to use juicefs-csi-driver with same Redis Sentinel configuration for metadata and data storage.
For metaurl this works:
```
redis://:my.PasS@k8s123,redis-sentinels-node-0.redis-sentinels-headless.redis-sentinels.svc.cluster.local,redis-sentinels-node-1.redis-sentinels-headless.redis-sentinels.svc.cluster.local,redis-sentinels-node-2.redis-sentinels-headless.redis-sentinels.svc.cluster.local:26379/0
```
But for bucket only this works:
```
redis://redis-sentinels-node-0.redis-sentinels-headless.redis-sentinels.svc.cluster.local:6379/0
```
If we try to use sentinel config for bucket we get these errors:
```
I0714 21:46:57.955318       8 controller.go:68] CreateVolume: Secrets contains keys [format-options metaurl name secret-key storage bucket envs]
I0714 21:46:57.956357       8 juicefs.go:600] ceFormat cmd: [/usr/local/bin/juicefs format --storage=file --bucket=redis://k8s123,redis-sentinels-node-0.redis-sentinels-headless.redis-sentinels.svc.cluster.local,redis-sentinels-node-1.redis-sentinels-headless.redis-sentinels.svc.cluster.local,redis-sentinels-node-2.redis-sentinels-headless.redis-sentinels.svc.cluster.local:26379/0 --access-key= --secret-key=${secretkey} ${metaurl} juice --capacity=1]
I0714 21:46:58.135037       8 juicefs.go:621] Format output is 
E0714 21:46:58.135120       8 driver.go:83] GRPC error: rpc error: code = Internal desc = Could not createVol in juicefs: rpc error: code = Internal desc = exit status 1
```

### PR DESCRIPTION
**Pull request by zhijian-pro**
Close #2366 
TODO:
- [x] implement cluster mode
- [x] Document

The redis of cluster mode as object storage passed  unit  test.

### CODE REVIEW

File: pkg/object/redis.go [hunk 1]
```diff
@@ -160,19 +163,70 @@ func (t *redisStore) Head(key string) (Object, error) {
...
+			c := redis.NewClient(opt)
+			info, err := c.ClusterInfo(context.Background()).Result()
+			if err != nil && strings.Contains(err.Error(), "cluster mode") || err == nil && strings.Contains(info, "cluster_state:") {
+				logger.Infof("redis %s is in cluster mode", hosts)
+			} else {
+				rdb = c
+			}
+		}
+		if rdb == nil {
+			logger.Fatalf("cluster mode redis is not supported as object storage for the time being")
```
Comment (davies) [inline pkg/object/redis.go:225]: cluster mode is OK here

File: pkg/object/redis.go [hunk 2]
```diff
@@ -160,19 +163,70 @@ func (t *redisStore) Head(key string) (Object, error) {
...
+		}
+		for i, addr := range fopt.SentinelAddrs {
+			h, p, e := net.SplitHostPort(addr)
+			if e != nil {
+				fopt.SentinelAddrs[i] = net.JoinHostPort(addr, port)
+			} else if p == "" {
+				fopt.SentinelAddrs[i] = net.JoinHostPort(h, port)
+			}
+		}
+		fopt.SentinelPassword = os.Getenv("SENTINEL_PASSWORD_FOR_OBJ")
```
Comment (davies) [inline pkg/object/redis.go:203]: update docs
