### PR TITLE
meta: check whether the value of slices is corrupt

### LINKED ISSUE #2873: fatal error: sync :unlock of unlocked mutex
fb130d09bf974607a8da3d0aaf1e921

### PR DESCRIPTION
**Pull request by SandyXSD**
fix #2873

### CODE REVIEW

File: pkg/meta/redis.go [hunk 1]
```diff
@@ -2119,7 +2122,11 @@ func (m *redisMeta) CopyFileRange(ctx Context, fin Ino, offIn uint64, fout Ino,
 			for _, v := range vals {
 				sv := v.(*redis.StringSliceCmd).Val()
 				// Add a zero chunk for hole
-				ss := append([]*slice{{len: ChunkSize}}, readSlices(sv)...)
```
Comment (davies) [inline pkg/meta/redis.go:2122]: Can sv be a empty list?

Comment (davies) [reply pkg/meta/redis.go:2122]: it's OK even `sv` is empty

**Review by davies — APPROVED** [review]
