### PR TITLE
cmd/mount: add `max-writeback-size` option to filter blocks for writeback

### LINKED ISSUE #6417: if use write back then upload large file very slow
**What happened**: when mount --write-back then dd  write large file speed change from 500MB/s to 100+ MB/s

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
juicefs mount --writeback(or not)
dd if=/dev/zero of=./$(hostname).40G bs=4096000 count=1000 

**Anything else we need to know?**

**Environment**:
- JuiceFS version :juicefs version 1.4.0-dev+2025-07-03.c7dadcb7
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`): ubuntu 22.04
- Kernel (e.g. `uname -a`):5.15.0-156-generic
- Object storage (cloud provider and region, or self maintained): aws s3 
- Metadata engine info (version, cloud provider managed or self maintained): redis 6
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

### PR DESCRIPTION
**Pull request by jiefenghuang**
close #6417
For most scenarios, enabling writeback and setting max-writeback-size = BlockSize can filter out sequential writes.

### CODE REVIEW

File: pkg/chunk/cached_store.go [hunk 1]
```diff
@@ -454,7 +454,7 @@ func (s *wSlice) upload(indx int) {
 		if off != blen {
 			panic(fmt.Sprintf("block length does not match: %v != %v", off, blen))
 		}
-		if s.writeback {
+		if s.writeback && blen < s.store.conf.MaxWritebackSize {
```
Comment (SandyXSD) [inline pkg/chunk/cached_store.go]:
```suggestion
		if s.writeback && blen <= s.store.conf.MaxWritebackSize {
```

File: pkg/chunk/cached_store.go [hunk 2]
```diff
@@ -635,6 +622,24 @@ func (c *Config) SelfCheck(uuid string) {
 		logger.Warnf("writeback is not supported in memory cache mode")
 		c.Writeback = false
 	}
+	if c.Writeback {
+		if !c.CacheFullBlock {
+			logger.Warnf("cache-partial-only is ineffective for stage blocks with writeback enabled")
+		}
+		if c.MaxWritebackSize == 0 {
+			c.MaxWritebackSize = c.BlockSize + 1
```
Comment (SandyXSD) [inline pkg/chunk/cached_store.go]:
```suggestion
			c.MaxWritebackSize = c.BlockSize
```

File: pkg/chunk/cached_store_test.go [hunk 3]
```diff
@@ -204,6 +204,7 @@ func TestForceUpload(t *testing.T) {
 	config := defaultConf
 	_ = os.RemoveAll(config.CacheDir)
 	config.Writeback = true
+	config.MaxWritebackSize = config.BlockSize + 1
```
Comment (SandyXSD) [inline pkg/chunk/cached_store_test.go]:
```suggestion
	config.MaxWritebackSize = config.BlockSize
```
