### PR TITLE
meta: fix delete slice

### LINKED ISSUE #6027: flaky test: TestFdbClient
https://github.com/juicedata/juicefs/actions/runs/14570487785/job/40866752154?pr=6026
```
=== RUN   TestFdbClient
20[25](https://github.com/juicedata/juicefs/actions/runs/14570487785/job/40866752154?pr=6026#step:10:26)/04/21 08:47:16.795239 juicefs[5295] <INFO>: Create session 1 OK with version: 1.3.0-dev+unknown [NewSession@base.go:519]
2025/04/21 08:47:17.050652 juicefs[5295] <INFO>: flush session 1: [FlushSession@base.go:706]
2025/04/21 08:47:17.053371 juicefs[5295] <INFO>: close session 1: <nil> [CloseSession@base.go:695]
2025/04/21 08:47:17.214980 juicefs[5295] <WARNING>: File name is too long as a trash entry, truncating it: fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff -> 1-24-ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff [trashEntry@base.go:2472]
2025/04/21 08:47:17.215206 juicefs[5295] <WARNING>: File name is too long as a trash entry, truncating it: fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff -> 1-24-ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff [trashEntry@base.go:2472]
2025/04/21 08:47:17.286223 juicefs[5295] <INFO>: cleanup trash: deleted 10 files in 35.152152ms [CleanupTrashBefore@base.go:25[26](https://github.com/juicedata/juicefs/actions/runs/14570487785/job/40866752154?pr=6026#step:10:27)]
2025/04/21 08:47:26.843788 juicefs[5295] <INFO>: Quota for inode 15 is deleted [loadQuotas@quota.go:288]
2025/04/21 08:47:48.256341 juicefs[5295] <INFO>: flush session 1: [FlushSession@base.go:706]
panic: send on closed channel

goroutine 515 [running]:
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).deleteSlice(0xc00046a508, 0x2e1c, 0x64)
	/home/runner/work/juicefs/juicefs/pkg/meta/base.go:2418 +0x17e
github.com/juicedata/juicefs/pkg/meta.(*kvMeta).doCompactChunk(0xc000064fa0, 0x1032, 0x0, {0xc000764a00, 0x2160, 0x2160}, {0xc000321808, 0x164, 0x164}, 0x0, ...)
	/home/runner/work/juicefs/juicefs/pkg/meta/tkv.go:2421 +0x773
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).compactChunk(0xc00046a508, 0x1032, 0x0, 0x0, 0x0)
	/home/runner/work/juicefs/juicefs/pkg/meta/base.go:2309 +0xf58
created by github.com/juicedata/juicefs/pkg/meta.(*baseMeta).Write in goroutine 121
	/home/runner/work/juicefs/juicefs/pkg/meta/base.go:1670 +0x3ef
FAIL	github.com/juicedata/juicefs/pkg/meta	31.541s
FAIL
make: *** [Makefile:102: test.fdb] Error 1
Error: Process completed with exit code 2.
```

### PR DESCRIPTION
**Pull request by jiefenghuang**
close #6027
only affect unittest

### CODE REVIEW

File: pkg/meta/base.go [hunk 1]
```diff
@@ -566,15 +568,14 @@ func (m *baseMeta) startDeleteSliceTasks() {
 }
 
 func (m *baseMeta) stopDeleteSliceTasks() {
-	m.Lock()
+	m.dSliceMu.Lock()
```
Comment (davies) [inline pkg/meta/base.go:571]: when dslices is full, this will be blocked, we should make sure that sessCtx is cancel before calling this.
