### PR TITLE
make dir stat flush period configrable

### LINKED ISSUE #3330: Flaky test: TestMySQLClient
**This problem has only recently appeared.**

=== RUN   TestMySQLClient
2023/03/13 16:20:40.146045 juicefs[25576] <ERROR>: error: Error 1146: Table 'dev.jfs_node' doesn't exist
goroutine [555](https://github.com/juicedata/juicefs/actions/runs/4407026427/jobs/7720109312#step:7:556)05 [running]:
runtime/debug.Stack()
	/opt/hostedtoolcache/go/1.19.7/x64/src/runtime/debug/stack.go:24 +0x65
github.com/juicedata/juicefs/pkg/meta.errno({0x1a959e0, 0xc0010cc1c8})
	/home/runner/work/juicefs/juicefs/pkg/meta/utils.go:105 +0x105
github.com/juicedata/juicefs/pkg/meta.(*dbMeta).doGetAttr(0xc00ac67700?, {0xc00ac7db60?, 0x0?}, 0xc00b215080?, 0x0?)
	/home/runner/work/juicefs/juicefs/pkg/meta/sql.go:817 +0x54
github.com/juicedata/juicefs/pkg/meta.(*baseMeta).GetAttr.func1()
	/home/runner/work/juicefs/juicefs/pkg/meta/base.go:818 +0x51
github.com/juicedata/juicefs/pkg/utils.WithTimeout.func1()
	/home/runner/work/juicefs/juicefs/pkg/utils/utils.go:76 +0x2f
created by github.com/juicedata/juicefs/pkg/utils.WithTimeout
	/home/runner/work/juicefs/juicefs/pkg/utils/utils.go:75 +0xdf [utils.go:105]
2023/03/13 16:20:40.565338 juicefs[2[557](https://github.com/juicedata/juicefs/actions/runs/4407026427/jobs/7720109312#step:7:558)6] <INFO>: Create session 1 OK with version: 1.1.0-dev+unknown [base.go:440]
2023/03/13 16:20:41.283969 juicefs[25576] <WARNING>: checking counter lastCleanupFiles: read-only file system [base.go:557]
2023/03/13 16:20:56.504549 juicefs[25576] <WARNING>: checking counter lastCleanupFiles: read-only file system [base.go:557]
2023/03/13 16:20:59.156686 juicefs[25576] <WARNING>: checking counter lastCleanupFiles: read-only file system [base.go:557]
2023/03/13 16:21:05.539988 juicefs[25576] <WARNING>: checking counter lastCleanupFiles: read-only file system [base.go:557]
2023/03/13 16:21:21.500533 juicefs[25576] <WARNING>: Already tried 50 times, returning: Error 1062: Duplicate entry '2' for key 'jfs_dir_stats.PRIMARY' [sql.go:693]
2023/03/13 16:21:21.500589 juicefs[25576] <WARNING>: sync dir stat for 2: Error 1062: Duplicate entry '2' for key 'jfs_dir_stats.PRIMARY' [base.go:258]
2023/03/13 16:21:21.50[562](https://github.com/juicedata/juicefs/actions/runs/4407026427/jobs/7720109312#step:7:563)1 juicefs[25576] <INFO>: close session 1: %!s(<nil>) [base.go:542]
2023/03/13 16:21:21.821709 juicefs[25576] <WARNING>: File name is too long as a trash entry, truncating it: fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff -> 1-20-ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff [base.go:1550]
2023/03/13 16:21:21.864628 juicefs[25576] <INFO>: cleanup trash: deleted 6 files in 36.388898ms [base.go:1586]
2023/03/13 16:21:28.897295 juicefs[25576] <WARNING>: checking counter lastCleanupFiles: read-only file system [base.go:557]
2023/03/13 16:21:36.586419 juicefs[25576] <WARNING>: checking counter lastCleanupFiles: read-only file system [base.go:557]
2023/03/13 16:21:39.920867 juicefs[25576] <WARNING>: checking counter lastCleanupFiles: read-only file system [base.go:557]
2023/03/13 16:21:53.036498 juicefs[25576] <INFO>: chunk 4135:1 was changed 72 -> 24 [sql.go:2593]
2023/03/13 16:21:53.040912 juicefs[25576] <INFO>: compacted chunk 1117 was not used [sql.go:2636]
2023/03/13 16:21:53.042933 juicefs[25576] <INFO>: compaction for 4135:1 is wasted, delete slice 1117 (67108864 bytes) [sql.go:2643]
2023/03/13 16:21:54.959676 juicefs[25576] <WARNING>: checking counter lastCleanupFiles: read-only file system [base.go:557]
2023/03/13 16:21:55.321207 juicefs[25576] <INFO>: chunk 4135:0 was changed 168 -> 120 [sql.go:2593]
2023/03/13 16:21:55.323903 juicefs[25576] <INFO>: compacted chunk 1355 was not used [sql.go:2636]
2023/03/13 16:21:55.324046 juicefs[25576] <INFO>: compaction for 4135:0 is wasted, delete slice 1355 (1000000 bytes) [sql.go:2643]
2023/03/13 16:21:57.[571](https://github.com/juicedata/juicefs/actions/runs/4407026427/jobs/7720109312#step:7:572)039 juicefs[25576] <WARNING>: checking counter lastCleanupFiles: read-only file system [base.go:557]
2023/03/13 16:21:59.450609 juicefs[25576] <INFO>: chunk 4136:1 was changed 72 -> 24 [sql.go:2593]
2023/03/13 16:21:59.451867 juicefs[25576] <INFO>: compacted chunk 1360 was not used [sql.go:2636]
2023/03/13 16:21:59.451926 juicefs[25576] <INFO>: compaction for 4136:1 is wasted, delete slice 1360 (67108864 bytes) [sql.go:2643]
2023/03/13 16:22:00.774615 juicefs[25576] <INFO>: chunk 4136:0 was changed 192 -> 120 [sql.go:2593]
2023/03/13 16:22:00.775861 juicefs[25576] <INFO>: compacted chunk 1598 was not used [sql.go:2636]
2023/03/13 16:22:00.775944 juicefs[25576] <INFO>: compaction for 4136:0 is wasted, delete slice 1598 (900000 bytes) [sql.go:2643]
2023/03/13 16:22:03.136459 juicefs[25576] <WARNING>: checking counter lastCleanupFiles: read-only file system [base.go:557]
2023/03/13 16:22:04.643463 juicefs[25576] <INFO>: Create session 2 OK with version: 1.1.0-dev+unknown [base.go:440]
2023/03/13 16:22:04.680339 juicefs[25576] <INFO>: close session 2: %!s(<nil>) [base.go:542]
2023/03/13 16:22:07.794900 juicefs[25576] <WARNING>: nlink of /check should be 3, but got 0 [base.go:1350]
2023/03/13 16:22:07.794939 juicefs[25576] <WARNING>: Path /check (inode 4459) can be repaired, please re-run with '--path /check --repair' to fix it [base.go:1377]
2023/03/13 16:22:07.798462 juicefs[25576] <WARNING>: nlink of /check should be 3, but got 0 [base.go:1350]
2023/03/13 16:22:07.808437 juicefs[25576] <WARNING>: nlink of /check/d1/d2 should be 3, but got 0 [base.go:1350]
2023/03/13 16:22:07.815415 juicefs[25576] <WARNING>: attribute of / is missing [base.go:1354]
2023/03/13 16:22:07.940326 juicefs[25576] <WARNING>: nlink of /check/d1 should be 3, but got 0 [base.go:1350]
2023/03/13 16:22:07.945021 juicefs[25576] <WARNING>: nlink of /check/d1/d2/d3 should be 3, but got 0 [base.go:1350]
2023/03/13 16:22:07.9[572](https://github.com/juicedata/juicefs/actions/runs/4407026427/jobs/7720109312#step:7:573)09 juicefs[25[576](https://github.com/juicedata/juicefs/actions/runs/4407026427/jobs/7720109312#step:7:577)] <WARNING>: nlink of /check/d1/d2/d3/d4 should be 2, but got 0 [base.go:1350]
    base_test.go:1886: test dir usage: expect {length:0 space:4096 inodes:1}, but got &{length:0 space:0 inodes:0}
--- FAIL: TestMySQLClient (92.77s)

### PR DESCRIPTION
**Pull request by Hexilee**
close #3330

### CODE REVIEW

File: pkg/meta/sql_test.go [hunk 1]
```diff
@@ -22,18 +22,23 @@ import (
 	"path"
 	"strings"
 	"testing"
+	"time"
 )
 
 func TestSQLiteClient(t *testing.T) {
-	m, err := newSQLMeta("sqlite3", path.Join(t.TempDir(), "jfs-unit-test.db"), DefaultConf())
+	conf := DefaultConf()
+	conf.DirStatFlushPeriod = 500 * time.Millisecond
```
Comment (davies) [inline pkg/meta/sql_test.go:30]: we can use 100ms for all tests

Comment (Hexilee) [reply pkg/meta/sql_test.go]: done
