### PR TITLE
meta/sql: fix dumpDir concurrent issue

### LINKED ISSUE #5928: CI: dump timeout with small mysql max open connections.
**What happened**:
try to dump with 50 threads
./juicefs dump '***(127.0.0.1)/test?max_open_conns=30' dump.json --threads=50

 the test finish in about 3 minutes when not set max open connections,
https://github.com/juicedata/juicefs/actions/runs/14227542944/job/39870879066

the test will timeout after 1 hour when set max open connections to 30.
https://github.com/juicedata/juicefs/actions/runs/14295694259/job/40062657454

**What you expected to happen**:
dump should not block with max open connection set to 30.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

### PR DESCRIPTION
**Pull request by jiefenghuang**
close #5928

fix error overwrite and index in retry

### CODE REVIEW

File: pkg/meta/sql.go [hunk 1]
```diff
@@ -3842,21 +3842,23 @@ func (m *dbMeta) dumpDir(s *xorm.Session, inode Ino, tree *DumpedEntry, bw *bufi
...
+	var threadErr error
 	for c := 0; c < threads; c++ {
 		conds[c] = sync.NewCond(&ms[c])
 		if c < len(entries) {
 			go func(c int) {
+				lastIdx := c
 				_ = m.roTxn(Background(), func(s *xorm.Session) error {
-					for i := c; i < len(entries) && err == nil; i += threads {
-						e := entries[i]
+					for ; lastIdx < len(entries) && threadErr == nil; lastIdx += threads {
```
Comment (davies) [inline pkg/meta/sql.go:3852]: it's better to move `for` out of roTxn
```
for {
    er := m.roTxn(func() {
          return m.dumpEntry()
    })

}
```
