### PR TITLE
meta/test: use random db name for sqlite tests

### LINKED ISSUE #516: Flaky test: TestStickyBitSQL
Sometimes, the TestStickyBitSQL case failed without any reason, we should look into that.

```
=== RUN   TestStickyBitSQL
[xorm] [info]  2021/06/12 08:43:27.207240 PING DATABASE sqlite3
FAIL	github.com/juicedata/juicefs/pkg/meta	1.467s
```

### PR DESCRIPTION
**Pull request by Sandy4999**
close #516

### CODE REVIEW

File: pkg/meta/sql_test.go [hunk 1]
```diff
@@ -17,13 +17,13 @@
...
-	"os"
 	"testing"
+
+	"github.com/juicedata/juicefs/pkg/utils"
 )
 
 func TestSQLClient(t *testing.T) {
-	os.Remove("test.db")
-	m, err := newSQLMeta("sqlite3", "test.db", &Config{})
+	m, err := newSQLMeta("sqlite3", utils.RandString(8)+".db", &Config{})
```
Comment (davies) [inline pkg/meta/sql_test.go:26]: Should we use `io/ioutil.TempFile()`?

Comment (suzaku) [reply pkg/meta/sql_test.go:26]: +1, it seems to be a good use case for `TempFile`.

Comment (Sandy4999) [reply pkg/meta/sql_test.go]: e326154
