### PR TITLE
cmd/sync: send the directory to be delayed for deletion to the manage node

### LINKED ISSUE #5770: Error "directory not empty" during delete-src
**What happened**:

CI test:
https://github.com/juicedata/juicefs/actions/runs/13804657097/job/38613105839

test case:
```
test_sync_with_random_test(){
    prepare_test
    ./juicefs mount -d $META_URL /jfs
    mkdir /jfs/test || true
    mkdir /jfs/test2 || true
    
    ./random-test runOp -baseDir /jfs/test -files 500000 -ops 5000000 -threads 50 -dirSize 10 -duration 60s -createOp 30,uniform \
    -deleteOp 5,end --linkOp 10,uniform --removeLinkOp 1,end --symlinkOp 20,uniform --setXattrOp 10,uniform --truncateOp 10,uniform
    chmod -R 777 /jfs/test
    chmod -R 777 /jfs/test2
    sudo -u juicedata meta_url=$META_URL ./juicefs sync jfs://meta_url/test/ jfs://meta_url/test2/ \
         --manager-addr 172.20.0.1:8081 --worker juicedata@172.20.0.2,juicedata@172.20.0.3 \
         --list-threads 10 --list-depth 5 --check-new --links \
         2>&1 | tee sync.log
    grep "panic:\|<FATAL>\|ERROR" sync.log && echo "panic or fatal in sync.log" && exit 1 || true
    sudo -u juicedata meta_url=$META_URL ./juicefs sync --delete-src --match-full-path jfs://meta_url/test/ jfs://meta_url/test2/ \
         --manager-addr 172.20.0.1:8081 --worker juicedata@172.20.0.2,juicedata@172.20.0.3 --dirs\
         --list-threads 10 --list-depth 5 --check-new \
         2>&1 | tee sync.log
    grep "panic:\|<FATAL>\|ERROR" sync.log && echo "panic or fatal in sync.log" && exit 1 || true
    [ -z "$(ls -A /jfs/test)" ] || exit 1
    rm -rf empty || mkdir empty
    sudo -u juicedata meta_url=$META_URL ./juicefs sync --delete-dst --match-full-path  --include='*' \
         ./empty/ jfs://meta_url/test2/ --manager-addr 172.20.0.1:8081 --worker juicedata@172.20.0.2,juicedata@172.20.0.3 \
         --list-threads 10 --list-depth 5 --check-new --dirs\
         2>&1 | tee sync.log
    grep "panic:\|<FATAL>" sync.log && echo "panic or fatal in sync.log" && exit 1 || true
    [ -z "$(ls -A /jfs/test2)" ] || exit 1
}
```

```
2025-03-12T05:59:43.0456507Z 2025/03/12 05:59:43.045410 juicefs[12285] <INFO>: delete 42200 dirs from jfs://myjfs/test/ [Sync@sync.go:1652]
2025-03-12T06:00:06.5190963Z 2025/03/12 06:00:06.518802 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_8/dir_8/ from jfs://myjfs/test/ in 5.003452983s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:00:11.5237106Z 2025/03/12 06:00:11.523453 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_8/dir_5/ from jfs://myjfs/test/ in 5.002921671s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:00:16.5276810Z 2025/03/12 06:00:16.527454 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_8/dir_9/ from jfs://myjfs/test/ in 5.002302153s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:00:21.5316579Z 2025/03/12 06:00:21.531379 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_8/dir_1/ from jfs://myjfs/test/ in 5.003867627s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:00:26.5377120Z 2025/03/12 06:00:26.537460 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_7/dir_3/ from jfs://myjfs/test/ in 5.00225266s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:00:31.5415531Z 2025/03/12 06:00:31.541269 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_7/dir_1/ from jfs://myjfs/test/ in 5.003755711s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:00:36.5452796Z 2025/03/12 06:00:36.545015 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_7/dir_2/ from jfs://myjfs/test/ in 5.0036971s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:00:41.5490881Z 2025/03/12 06:00:41.548836 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_7/dir_9/ from jfs://myjfs/test/ in 5.002479194s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:00:46.5553194Z 2025/03/12 06:00:46.555021 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_5/dir_7/ from jfs://myjfs/test/ in 5.003362535s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:00:51.5603853Z 2025/03/12 06:00:51.560098 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_5/dir_9/ from jfs://myjfs/test/ in 5.002758481s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:00:56.5657357Z 2025/03/12 06:00:56.565467 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_4/dir_7/ from jfs://myjfs/test/ in 5.00357314s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:01:01.5692781Z 2025/03/12 06:01:01.568960 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_4/dir_8/ from jfs://myjfs/test/ in 5.003424312s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:01:06.5767257Z 2025/03/12 06:01:06.576451 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_4/dir_0/ from jfs://myjfs/test/ in 5.002738922s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:01:11.5799195Z 2025/03/12 06:01:11.579649 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_4/dir_1/ from jfs://myjfs/test/ in 5.003150238s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:01:16.5838689Z 2025/03/12 06:01:16.583633 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_6/dir_7/ from jfs://myjfs/test/ in 5.003929565s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:01:21.5885445Z 2025/03/12 06:01:21.588273 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_6/dir_3/ from jfs://myjfs/test/ in 5.002274676s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:01:26.5935729Z 2025/03/12 06:01:26.593313 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_6/dir_1/ from jfs://myjfs/test/ in 5.00316848s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:01:31.5973186Z 2025/03/12 06:01:31.596997 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_6/dir_9/ from jfs://myjfs/test/ in 5.003634353s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:01:36.6009449Z 2025/03/12 06:01:36.600681 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_6/dir_0/ from jfs://myjfs/test/ in 5.003632695s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:01:41.6050770Z 2025/03/12 06:01:41.604771 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_3/dir_3/ from jfs://myjfs/test/ in 5.002929129s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:01:46.6085013Z 2025/03/12 06:01:46.608223 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_3/dir_2/ from jfs://myjfs/test/ in 5.003391989s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:01:51.6125969Z 2025/03/12 06:01:51.612298 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_3/dir_6/ from jfs://myjfs/test/ in 5.002836298s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:01:56.6173081Z 2025/03/12 06:01:56.617018 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_2/dir_8/ from jfs://myjfs/test/ in 5.003522597s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:02:01.6224798Z 2025/03/12 06:02:01.622185 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_2/dir_7/ from jfs://myjfs/test/ in 5.003902784s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:02:06.6276931Z 2025/03/12 06:02:06.627402 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_2/dir_0/ from jfs://myjfs/test/ in 5.003202695s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:02:11.6319606Z 2025/03/12 06:02:11.631666 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_2/dir_3/ from jfs://myjfs/test/ in 5.004207758s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:02:16.6368698Z 2025/03/12 06:02:16.636625 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_2/dir_2/ from jfs://myjfs/test/ in 5.002856045s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:02:21.6401213Z 2025/03/12 06:02:21.639837 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_2/dir_1/ from jfs://myjfs/test/ in 5.003160954s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:02:26.6469660Z 2025/03/12 06:02:26.646718 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_7/dir_3/dir_3/ from jfs://myjfs/test/ in 5.002939194s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:02:31.6548838Z 2025/03/12 06:02:31.654621 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_7/dir_3/dir_2/ from jfs://myjfs/test/ in 5.003568358s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:02:36.6608360Z 2025/03/12 06:02:36.660551 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_0/dir_4/ from jfs://myjfs/test/ in 5.003274158s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:02:41.6665221Z 2025/03/12 06:02:41.666246 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_0/dir_6/ from jfs://myjfs/test/ in 5.004274215s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:02:46.6705453Z 2025/03/12 06:02:46.670305 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_0/dir_2/ from jfs://myjfs/test/ in 5.004006862s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:02:51.6741863Z 2025/03/12 06:02:51.673920 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_0/dir_3/ from jfs://myjfs/test/ in 5.003566557s: directory not empty [deleteObj@sync.go:233]
2025-03-12T06:02:56.6778455Z 2025/03/12 06:02:56.677566 juicefs[12285] <ERROR>: Failed to delete dir_4/dir_8/dir_0/dir_9/ from jfs://myjfs/test/ in 5.003601856s: directory not empty [deleteObj@sync.go:233]
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

### PR DESCRIPTION
**Pull request by zhijian-pro**
fix #5770

### CODE REVIEW

File: pkg/sync/cluster.go [hunk 1]
```diff
@@ -91,13 +94,24 @@ func httpRequest(url string, body []byte) (ans []byte, err error) {
 var sendStatMu sync.Mutex
 
 func sendStats(addr string) {
+	var dirs []string
+LOOP:
+	for len(dirs) < 5000 {
```
Comment (davies) [inline pkg/sync/cluster.go:99]: How to retry once it reach the limit?

File: pkg/sync/sync.go [hunk 2]
```diff
@@ -828,7 +828,17 @@ func worker(tasks <-chan object.Object, src, dst object.ObjectStorage, config *C
 				break
 			} else if equal {
 				if config.DeleteSrc {
-					deleteObj(src, key, false)
+					if obj.IsDir() {
+						if config.Manager != "" {
+							srcDelayDelDir <- key
+						} else {
+							SrcDelayDelMu.Lock()
+							SrcDelayDel = append(SrcDelayDel, key)
```
Comment (davies) [inline pkg/sync/sync.go:836]: why not use the same  in the worker?

File: pkg/sync/cluster.go [hunk 3]
```diff
@@ -91,13 +94,24 @@ func httpRequest(url string, body []byte) (ans []byte, err error) {
...
+		}
+	}
 	sendStatMu.Lock()
 	defer sendStatMu.Unlock()
 	var r Stat
 	r.Skipped = skipped.Current()
 	r.SkippedBytes = skippedBytes.Current()
 	r.Copied = copied.Current()
 	r.CopiedBytes = copiedBytes.Current()
+	r.DelayDelDir = dirs
```
Comment (davies) [inline pkg/sync/cluster.go:114]: add it back if fail to send

File: pkg/sync/cluster.go (hunk 1 above)
Comment (zhijian-pro) [reply pkg/sync/cluster.go]: Send no more than 5000 each time, if it exceeds 5000, leave it for the next send, and before the worker exits, check whether all have been sent.

File: pkg/sync/cluster.go [hunk 4]
```diff
@@ -98,6 +99,14 @@ func sendStats(addr string) {
 	r.SkippedBytes = skippedBytes.Current()
 	r.Copied = copied.Current()
 	r.CopiedBytes = copiedBytes.Current()
+	SrcDelayDelMu.Lock()
+	idx := len(SrcDelayDel)
+	if idx > 5000 {
```
Comment (davies) [inline pkg/sync/cluster.go:104]: no, other wise we can't make sure that all the path are sent to manager

File: pkg/sync/sync.go [hunk 5]
```diff
@@ -927,8 +933,8 @@ func (o *withFSize) Size() int64 {
 
 var dstDelayDelMu sync.Mutex
 var dstDelayDel []string
-var srcDelayDelMu sync.Mutex
-var srcDelayDel []string
+var SrcDelayDelMu sync.Mutex
+var SrcDelayDel []string
```
Comment (davies) [inline pkg/sync/sync.go:937]: ?

File: pkg/sync/cluster.go (hunk 1 above)
Comment (davies) [reply pkg/sync/cluster.go]: is it neccessary?
