### PR TITLE
pkg/sync: ignore not exist keys with checkpoint

### LINKED ISSUE #6876: sync: After the original data is deleted, the checkpoint file needs to have a verification
**What happened**:
```

1、 ./juicefs sync /root/chenyunhui/ /juicefs3/chenyunhui/ --enable-checkpoint --checkpoint-interval 1s --threads 100 --match-full-path --dirs --ignore-existing  --perms --links --inplace --check-change --list-threads 10 --list-depth 5
2、 delete /root/chenyunhui/data
3、 ./juicefs sync /root/chenyunhui/ /juicefs3/chenyunhui/ --enable-checkpoint --checkpoint-interval 1s --threads 100 --match-full-path --dirs --ignore-existing  --perms --links --inplace --check-change --list-threads 10 --list-depth 5

026/04/10 12:01:37.648989 juicefs[2549901] <ERROR>: Failed to copy object abc/random-test2/dir_26/dir_85/file_56: open /root/chenyunhui/abc/random-test2/dir_26/dir_85/file_56: no such file or directory [worker@sync.go:1109]
2026/04/10 12:01:37.649010 juicefs[2549901] <ERROR>: Failed to copy object abc/random-test2/dir_105/dir_333/file_316: open /root/chenyunhui/abc/random-test2/dir_105/dir_333/file_316: no such file or directory [worker@sync.go:1109]
2026/04/10 12:01:37.648903 juicefs[2549901] <ERROR>: Failed to copy object abc/random-test2/dir_80/dir_192/: open /root/chenyunhui/abc/random-test2/dir_80/dir_192: no such file or directory [worker@sync.go:1109]
2026/04/10 12:01:37.649104 juicefs[2549901] <ERROR>: copy link failed: readlink /root/chenyunhui/abc/random-test2/dir_105/dir_333/file_97.3242206.symlink: no such file or directory [worker@sync.go:1075]
```
After that, the sync will keep failing

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

### PR DESCRIPTION
**Pull request by zxh326**
fix: https://github.com/juicedata/juicefs/issues/6876

### CODE REVIEW

File: pkg/sync/checkpoint.go [hunk 1]
```diff
@@ -565,10 +566,14 @@ func (m *CheckpointManager) SaveOnSignal() {
...
 
-func trackCheckpointCompletion(key string, failed bool, mgr *CheckpointManager, config *Config) {
+func trackCheckpointCompletion(key string, err error, mgr *CheckpointManager, config *Config) {
 	if !config.EnableCheckpoint {
 		return
 	}
+	failed := err != nil
+	if errors.Is(err, os.ErrNotExist) {
+		failed = false
+	}
```
[the remark this answers is not in the document]
Comment (zxh326) [reply pkg/sync/checkpoint.go:576]: When a restored pending key is found to be already gone, we only clean up checkpoint state so the next resume does not keep carrying stale failed entries. We are not trying to turn that condition into a successful result for the current run.

File: pkg/sync/checkpoint.go [hunk 2]
```diff
@@ -565,10 +566,14 @@ func (m *CheckpointManager) SaveOnSignal() {
 	}()
 }
 
-func trackCheckpointCompletion(key string, failed bool, mgr *CheckpointManager, config *Config) {
+func trackCheckpointCompletion(key string, err error, mgr *CheckpointManager, config *Config) {
 	if !config.EnableCheckpoint {
 		return
 	}
+	failed := err != nil
+	if errors.Is(err, os.ErrNotExist) {
```
Comment (jiefenghuang) [inline pkg/sync/checkpoint.go:574]: 对象存储返回的错误码是否匹配? 404 中间有转换吗

File: pkg/sync/sync.go [hunk 3]
```diff
@@ -955,6 +955,13 @@ func CopyData(src, dst object.ObjectStorage, key string, size int64, calChksum b
 				srcChksum, err = doCopyMultiple(src, dst, key, size, upload, calChksum)
 			}
 		}
+		if err != nil {
```
Comment (jiefenghuang) [inline pkg/sync/sync.go]: 把这个判断放到外层, line 968更好一些?  doCopySingle中也不需要单独处理

**Review by jiefenghuang — APPROVED** [review]
