### PR TITLE
cmd/debug: support for information collection mode in dual-process mode

### LINKED ISSUE #4811: debug command can't work with latest mount process
**What happened**:
root@bench-01:~/juicefs# ./juicefs debug /tmp/jfs

Platform:
linux amd64

Kernel:
Linux version 5.4.0-131-generic (buildd@lcy02-amd64-108) (gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1)) #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022

OS:
LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal

2024/05/06 11:04:51.040644 juicefs[996347] <FATAL>: failed to get mount command: find more than one mount process for /tmp/jfs [main.go:31]

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

### PR DESCRIPTION
**Pull request by zhijian-pro**
close #4811

### CODE REVIEW

File: cmd/debug.go [hunk 1]
```diff
@@ -122,12 +122,33 @@ func copyFile(srcPath, destPath string, requireRootPrivileges bool) error {
...
+		content, err := readConfig(mp)
+		if err != nil {
+			logger.Warnf("failed to read config file: %v", err)
+		}
+		cfg := vfs.Config{}
+		if err := json.Unmarshal(content, &cfg); err != nil {
+			logger.Warnf("failed to unmarshal config file: %v", err)
+		}
+		if cfg.Pid != 0 {
+			pid = strconv.Itoa(cfg.Pid)
```
Comment (SandyXSD) [inline cmd/debug.go:135]: We need a standalone `pid` within this function.
