### PR TITLE
vfs: invalid entry cache after `rmr`

### LINKED ISSUE #2767: file still exist after rmr file returned succeed.
**What happened**:

https://github.com/juicedata/juicefs/actions/runs/3059989787/jobs/4937989461

./juicefs-1.0.0 format redis://localhost/1 test-volume --block-size 225 --compress lz4 --shards 1 --storage minio --capacity 1 --inodes 1050368 --trash-days 7421 --encrypt-rsa-key my-priv-key.pem --bucket http://localhost:9000/test-bucket --access-key minioadmin --secret-key minioadmin --debug
./juicefs-1.0.0 mount -d redis://localhost/1 /tmp/sync-test/ --log ~/.juicefs/juicefs.log -o writeback_cache,debug,allow_other --attr-cache 8 --entry-cache 1 --dir-entry-cache 7 --get-timeout 47 --put-timeout 48 --io-retries 8 --max-uploads 76 --max-deletes 58 --buffer-size 438 --upload-limit 754 --download-limit 410 --prefetch 50 --upload-delay 0 --cache-dir ~/.juicefs/cache2 --cache-size 0 --free-space-ratio 0.49999999999999994 --cache-partial-only --backup-meta 332 --heartbeat 7 --open-cache 60 --metrics 127.0.0.1:9568 --debug
./juicefs-1.0.0 umount /tmp/sync-test/ --debug
./juicefs-1.0.0 mount -d redis://localhost/1 /tmp/sync-test/ --log ~/.juicefs/juicefs.log --attr-cache 8 --entry-cache 2 --dir-entry-cache 2 --get-timeout 59 --put-timeout 31 --io-retries 15 --max-uploads 2 --max-deletes 1 --buffer-size 465 --upload-limit 14 --download-limit 783 --prefetch 1 --upload-delay 0 --cache-dir ~/.juicefs/cache1 --cache-size 1024000 --free-space-ratio 0.49999999999999994 --backup-meta 857 --heartbeat 7 --no-bgjob --open-cache 1 --metrics 127.0.0.1:9567 --debug
./juicefs-1.0.0 fsck redis://localhost/1 --debug
./juicefs-1.1.0-dev rmr /tmp/sync-test//file_to_rmr --debug

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

### LINKED ISSUE #2769: rmr report "no such file or directory" when file exist.
**What happened**:
https://github.com/juicedata/juicefs/actions/runs/3060700916/jobs/4939536789
```

start rmr
run_cmd:dd if=/dev/urandom of=/tmp/sync-test//file_to_rmr bs=1048576 count=3
3+0 records in
3+0 records out
3145728 bytes (3.1 MB, 3.0 MiB) copied, 0.0708432 s, 44.4 MB/s

run_cmd succeed
run_jfs_cmd:./juicefs-1.1.0-dev rmr /tmp/sync-test//file_to_rmr --debug
   --trash-days value       number of days after which removed files will be permanently deleted (default: 1)
run_jfs_cmd return code: 0, output: 
run_jfs_cmd succeed
rmr succeed
start dump
run_jfs_cmd:./juicefs-1.1.0-dev dump tikv://127.0.0.1:2379 dump.json --debug
run_jfs_cmd return code: 0, output: 2022/09/15 13:13:16.725644 juicefs[11646] <INFO>: Meta address: tikv://127.0.0.1:2379 [interface.go:411]
[2022/09/15 13:13:16.725 +00:00] [INFO] [client.go:378] ["[pd] create pd client with endpoints"] [pd-address="[127.0.0.1:2379]"]
[2022/09/15 13:13:16.728 +00:00] [INFO] [base_client.go:350] ["[pd] switch leader"] [new-leader=http://127.0.0.1:2379]/ [old-leader=]
[2022/09/15 13:13:16.728 +00:00] [INFO] [base_client.go:105] ["[pd] init cluster id"] [cluster-id=7143593052261163827]
[2022/09/15 13:13:16.728 +00:00] [INFO] [client.go:673] ["[pd] tso dispatcher created"] [dc-location=global]
[2022/09/15 13:13:16.829 +00:00] [WARN] [pd.go:152] ["get timestamp too slow"] ["cost time"=100.756022ms]
2022/09/15 13:13:16.845838 juicefs[11646] <WARNING>: Secret key is removed for the sake of safety [tkv.go:2592]
2022/09/15 13:13:16.846724 juicefs[11646] <INFO>: Dump metadata into dump.json succeed [dump.go:80]

run_jfs_cmd succeed
dump succeed
start rmr
run_cmd:dd if=/dev/urandom of=/tmp/sync-test//file_to_rmr bs=1048576 count=3
3+0 records in
3+0 records out
3145728 bytes (3.1 MB, 3.0 MiB) copied, 0.0631098 s, 49.8 MB/s

run_cmd succeed
run_jfs_cmd:./juicefs-1.1.0-dev rmr /tmp/sync-test//file_to_rmr --debug
<FATAL>: subprocess run error, return code: 1 , error message: 2022/09/15 13:13:17.324990 juicefs[11658] <FATAL>: RMR /tmp/sync-test//file_to_rmr: no such file or directory [rmr.go:105]
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region, or self maintained):
- Metadata engine info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to metadata engine, JuiceFS to object storage):
- Others:

### PR DESCRIPTION
**Pull request by SandyXSD**
close #2769 
close #2767 

`DeleteNotify` is not used for simplicity because the child inode can't be obtained directly.
See: https://github.com/juicedata/go-fuse/blob/master/fuse/server.go#L767

### CODE REVIEW

File: pkg/vfs/vfs.go [hunk 1]
```diff
@@ -905,6 +905,7 @@ type VFS struct {
 	Conf   *Config
 	Meta   meta.Meta
 	Store  chunk.ChunkStore
+	RmrCB  func(parent meta.Ino, name string) syscall.Errno
```
Comment (davies) [inline pkg/vfs/vfs.go:908]: RmrCB -> InvalidEntry
