### PR TITLE
Keep SGID for directory

### LINKED ISSUE #1132: Directory keep SGID
**What happened**:
```bash
mkdir dir1
chmod g+s  dir1
chown admin:yarn dir1
```
We lost SGID on the directory.

**What you expected to happen**:
SGID should be kept when chown directory.

**How to reproduce it (as minimally and precisely as possible)**:
```bash
mkdir dir1
chmod g+s  dir1
chown admin:yarn dir1
```

**Anything else we need to know?**

**Environment**:
- JuiceFS version (use `./juicefs --version`) or Hadoop Java SDK version:
- Cloud provider or hardware configuration running JuiceFS:
- OS (e.g: `cat /etc/os-release`):
- Kernel (e.g. `uname -a`):
- Object storage (cloud provider and region):
- Redis info (version, cloud provider managed or self maintained):
- Network connectivity (JuiceFS to Redis, JuiceFS to object storage):
- Others:

### PR DESCRIPTION
**Pull request by davies**
The man page of chown does not mention the behavior for directory, so we keep the behavior close to ext3/ext4 in Linux.

In macOS (darwin), we pick the behavior in APFS.

close #1132

### CODE REVIEW

File: pkg/meta/sql.go [hunk 1]
```diff
@@ -598,6 +598,30 @@ func (m *dbMeta) doGetAttr(ctx Context, inode Ino, attr *Attr) syscall.Errno {
 	return errno(err)
 }
 
+func clearSGIDSQL(ctx Context, cur *node, set *Attr) {
```
Comment (SandyXSD) [inline pkg/meta/sql.go:601]: maybe make cur an interface{} ?

File: pkg/meta/base.go [hunk 2]
```diff
@@ -340,6 +341,30 @@ func (m *baseMeta) marshal(attr *Attr) []byte {
 	return w.Bytes()
 }
 
+func clearSGID(ctx Context, cur *Attr, set *Attr) {
```
Comment (SandyXSD) [inline pkg/meta/base.go:344]: the name is a bit misleading since it may clear SUID as well

File: pkg/meta/sql.go (hunk 1 above)
Comment (davies) [reply pkg/meta/sql.go:601]: not worth it

**Review by SandyXSD — APPROVED** [review]
